// Command hookfailgen propagates the one authored hookfailures package into every plugin module.
//
// Dev tooling for this repository only. Nothing here ships to an installing project.
//
// # Why copies at all
//
// The same reason buildidgen copies: each plugin's tools/ must build alone (`sc-doctor --fix`
// builds from the installed plugin root), so the modules are separate by design and a shared
// import is not available.
//
// # Why this package is worth generating rather than writing three times
//
// It is the one answer to a defect all three plugins had: a hook exits 0 by contract, so every
// failure it reported on stderr reached the debug log and nobody. gray-area's copy (#990) proved
// the shape in the field; three hand-kept copies of it would drift, and the drift would be silent
// in exactly the way the package exists to prevent.
//
// The copies are BYTE-IDENTICAL. What differs per plugin — the record directory's name — is a
// parameter the caller passes to New, never a value written into the file, so `-check` can assert
// the one property that matters: the three modules carry the same code.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ctoforaday/special-circumstances/scripts/internal/gitx"
)

// srcDir is the authored package. targets are the modules that need a copy of it.
const srcDir = "scripts/internal/hookfailures"

var targets = []string{
	"plugins/prosthetic-conscience/tools/internal/hookfailures",
	"plugins/gray-area/tools/internal/hookfailures",
	"plugins/frank-exchange-of-views/tools/internal/hookfailures",
}

func main() {
	check := flag.Bool("check", false, "verify every copy matches the authored source instead of writing them")
	flag.Parse()

	root, err := gitx.Root()
	if err != nil {
		fmt.Fprintln(os.Stderr, "hookfailgen:", err)
		os.Exit(1)
	}
	want, err := render(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "hookfailgen:", err)
		os.Exit(1)
	}

	var stale []string
	for _, t := range targets {
		for name, body := range want {
			path := filepath.Join(root, t, name)
			if !*check {
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					fmt.Fprintln(os.Stderr, "hookfailgen:", err)
					os.Exit(1)
				}
				if err := os.WriteFile(path, body, 0o644); err != nil {
					fmt.Fprintln(os.Stderr, "hookfailgen:", err)
					os.Exit(1)
				}
				continue
			}
			got, err := os.ReadFile(path)
			if err != nil {
				stale = append(stale, fmt.Sprintf("%s/%s is missing (%v)", t, name, err))
				continue
			}
			if !bytes.Equal(got, body) {
				stale = append(stale, fmt.Sprintf("%s/%s has drifted from %s/%s", t, name, srcDir, name))
			}
		}
	}

	if !*check {
		fmt.Printf("hookfailgen: wrote %d file(s) into %d module(s)\n", len(want), len(targets))
		return
	}
	if len(stale) > 0 {
		for _, s := range stale {
			fmt.Fprintln(os.Stderr, "hookfailgen:", s)
		}
		fmt.Fprintf(os.Stderr, "hookfailgen: edit %s and run `(cd scripts && go run ./hookfailgen)` — "+
			"the copies are generated so the rule they carry is stated once.\n", srcDir)
		os.Exit(1)
	}
	fmt.Printf("hookfailgen: %d module(s) match %s\n", len(targets), srcDir)
}

// render reads the authored package and returns each file's generated form.
func render(root string) (map[string][]byte, error) {
	entries, err := os.ReadDir(filepath.Join(root, srcDir))
	if err != nil {
		return nil, err
	}
	out := map[string][]byte{}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		body, err := os.ReadFile(filepath.Join(root, srcDir, name))
		if err != nil {
			return nil, err
		}
		var b bytes.Buffer
		fmt.Fprintf(&b, "// Code generated by scripts/hookfailgen from %s/%s. DO NOT EDIT.\n\n", srcDir, name)
		b.Write(body)
		out[name] = b.Bytes()
	}
	// An authored package that reads as EMPTY would generate nothing and report success,
	// leaving whatever is already in the modules untouched and unchecked.
	if len(out) == 0 {
		return nil, fmt.Errorf("%s holds no non-test .go files — refusing to generate nothing", srcDir)
	}
	return out, nil
}
