// Command classgen derives the gap-class vocabulary Go tests stage from, out of the registry
// that actually ships it.
//
// Dev tooling for this repository only. Nothing here ships to an installing project.
//
// # Why generate rather than guard
//
// feov-memory/class-registry.json is the shipped vocabulary: `record.StageForRun` writes it
// into a run, and mint validation refuses a class that is not in it. Three test files each
// restated all 38 slugs by hand, under a comment saying "mirrors feov-memory/
// class-registry.json" — and nothing compared them. They were in sync when this was written,
// verified; the failure is what happens LATER. Rename a slug in the registry and the fixtures
// go on validating a vocabulary production no longer accepts, green the whole time, because
// the tests stage the class they also assert.
//
// The repository's own rule says to prefer GENERATING a derived carrier and gating staleness
// over guarding two hand-written copies, and this is exactly that shape: one authored record,
// several derived readers. So the Go copy is generated from the JSON and this command is also
// the gate — `-check` regenerates in memory and fails if the committed file has drifted.
//
// # Why a committed file rather than reading the JSON at test time
//
// The registry lives at the repository root, OUTSIDE the module that needs it, so `go:embed`
// cannot reach it. Reading it at runtime would make every test binary depend on locating the
// repository root — the dependency `internal/record`'s own fixture comment refuses, because a
// test that hunts for the repo root breaks when files move. A committed generated file has
// neither problem, and `-check` is what keeps it honest.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"

	"github.com/ctoforaday/special-circumstances/scripts/internal/gitx"
)

const (
	registryPath = "feov-memory/class-registry.json"
	outPath      = "plugins/frank-exchange-of-views/tools/internal/record/recordtest/classes_gen.go"
)

type registry struct {
	Classes []struct {
		Slug string `json:"slug"`
	} `json:"classes"`
}

func main() {
	check := flag.Bool("check", false, "verify the committed file matches the registry instead of writing it")
	flag.Parse()

	root, err := gitx.Root()
	if err != nil {
		fmt.Fprintln(os.Stderr, "classgen:", err)
		os.Exit(1)
	}
	want, err := generate(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "classgen:", err)
		os.Exit(1)
	}
	target := filepath.Join(root, outPath)

	if !*check {
		if err := os.WriteFile(target, want, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "classgen:", err)
			os.Exit(1)
		}
		fmt.Printf("classgen: wrote %s\n", outPath)
		return
	}

	got, err := os.ReadFile(target)
	if err != nil {
		fmt.Fprintf(os.Stderr, "classgen: %s is missing (%v) — run `go run ./classgen` in scripts/\n", outPath, err)
		os.Exit(1)
	}
	if !bytes.Equal(got, want) {
		fmt.Fprintf(os.Stderr, "classgen: %s is STALE against %s.\n"+
			"The gap-class vocabulary moved and the generated copy did not, so fixtures are staging a\n"+
			"vocabulary that may no longer be the shipped one — the tests would stay green either way,\n"+
			"because they assert the classes they themselves stage.\n"+
			"Regenerate: (cd scripts && go run ./classgen)\n", outPath, registryPath)
		os.Exit(1)
	}
	fmt.Printf("classgen: %s matches %s\n", filepath.Base(outPath), registryPath)
}

func generate(root string) ([]byte, error) {
	raw, err := os.ReadFile(filepath.Join(root, registryPath))
	if err != nil {
		return nil, err
	}
	var reg registry
	if err := json.Unmarshal(raw, &reg); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", registryPath, err)
	}
	slugs := make([]string, 0, len(reg.Classes))
	for _, c := range reg.Classes {
		if c.Slug != "" {
			slugs = append(slugs, c.Slug)
		}
	}
	// A registry that parses to NO classes must not silently generate an empty vocabulary:
	// every fixture would then stage nothing, every class would be refused, and the failure
	// would look like a hundred broken tests rather than one broken file.
	if len(slugs) == 0 {
		return nil, fmt.Errorf("%s parsed to ZERO classes — refusing to generate an empty vocabulary", registryPath)
	}
	sort.Strings(slugs)

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by scripts/classgen from %s. DO NOT EDIT.

package recordtest

// ShippedClasses is the gap-class vocabulary the plugin actually ships, in the order the
// registry holds it after sorting.
//
// Fixtures stage this rather than restating it. Three test files used to carry their own
// hand-written copy of all %d slugs, under a comment pointing at the registry and nothing
// comparing them to it — so a rename would have left every fixture validating a vocabulary
// production had stopped accepting, with the suite green throughout.
var ShippedClasses = []string{
`, registryPath, len(slugs))
	for _, s := range slugs {
		fmt.Fprintf(&b, "\t%q,\n", s)
	}
	fmt.Fprintln(&b, "}")
	return format.Source(b.Bytes())
}
