package anchor

import (
	"reflect"
	"strings"
	"testing"
)

// ONE SENTENCE RULE. Each row is a shape a reader of an anchor's sentence met: a terminator that
// ends nothing ("3.5%", "e.g.,", "verify_91.py"), a soft wrap, a closer before an anchor, and each
// condition by which markdown opens a block. The stated splits ("Dr.", "et al.") are pinned so
// changing them is a decision.
func TestSentences(t *testing.T) {
	const c = "<!--cite:c-1-->"
	P, L, H, T, F := Paragraph, ListItem, Heading, TableRow, Fence
	for _, r := range []struct {
		in    string
		want  []string
		kinds []BlockKind // checked when set
	}{
		// Terminators.
		{"Prices rose 3.5% in 2024. Then fell.", []string{"Prices rose 3.5% in 2024.", "Then fell."}, nil},
		{"Some bases (e.g., 3) fool it.", []string{"Some bases (e.g., 3) fool it."}, nil},
		{"Run scripts/verify_91.py to check.", []string{"Run scripts/verify_91.py to check."}, nil},
		{"Sources include numbers.education and OEIS.", []string{"Sources include numbers.education and OEIS."}, nil},
		{"√91 ≈ 9.54, so we test 2–9.", []string{"√91 ≈ 9.54, so we test 2–9."}, nil},
		{"see e.g.\nfoo bar.", []string{"see e.g.\nfoo bar."}, nil},
		{"He said “Stop.” Then he left.", []string{"He said “Stop.”", "Then he left."}, nil},
		{"Dr. Smith agrees.", []string{"Dr.", "Smith agrees."}, nil},
		{"Smith et al. (2020) found X.", []string{"Smith et al.", "(2020) found X."}, nil},
		// A soft wrap is whitespace.
		{"methods\nwith zero disagreement among them. The", []string{"methods\nwith zero disagreement among them.", "The"}, nil},
		{"First.\nSecond.", []string{"First.", "Second."}, []BlockKind{P}},
		{"A list:\n- one\n- two", []string{"A list:", "one", "two"}, []BlockKind{P, L, L}},
		{"Intro.\n```\nA. B.\n```\nAfter.", []string{"Intro.", "```\nA. B.\n```", "After."}, []BlockKind{P, F, P}},
		// An anchor after a closer belongs to the closer's sentence; the boundary is tested again
		// after it. After whitespace, or flush after a bare terminator, it opens the next one.
		{"**Wet.**" + c + " Next sentence.", []string{"**Wet.**" + c, "Next sentence."}, nil},
		{"**Wet.**" + c + " and more.", []string{"**Wet.**" + c + " and more."}, nil},
		{"Seen (p. 3.)" + c + " Next.", []string{"Seen (p. 3.)" + c, "Next."}, nil},
		{"One. " + c + ". Two.", []string{"One.", c + ".", "Two."}, nil},
		{"One." + c + " Two.", []string{"One.", c + " Two."}, nil},
		// Block openers, one row per condition.
		{"Text\n# Heading\nMore", []string{"Text", "# Heading", "More"}, []BlockKind{P, H, P}},
		{"Text\n#\nMore", []string{"Text", "#", "More"}, []BlockKind{P, H, P}},
		{"Fixed in\n#552 after review. Next.", []string{"Fixed in\n#552 after review.", "Next."}, []BlockKind{P}},
		{"Values differ\n| sharply here. Then more.\nAnd so on.", []string{"Values differ\n| sharply here.", "Then more.", "And so on."}, []BlockKind{P}},
		{"| a | b |\n| --- | --- |\n| c | d |", []string{"| a | b |", "| --- | --- |", "| c | d |"}, []BlockKind{T, T, T}},
		{"The steps are\n2. compute it. Done.", []string{"The steps are\n2. compute it.", "Done."}, []BlockKind{P}},
		{"Steps:\n1. compute it.\n2. check it.", []string{"Steps:", "compute it.", "check it."}, []BlockKind{P, L, L}},
		{"- one\n2. two", []string{"one\n2. two"}, []BlockKind{L}},
		{"Intro.\n\n3. starts a list.", []string{"Intro.", "starts a list."}, []BlockKind{P, L}},
		{"Claimed here.\n[^a]: https://example.org", []string{"Claimed here.", "[^a]: https://example.org"}, []BlockKind{P, FootnoteDef}},
		// Block quotes: a continuation ">" reads as whitespace; a ">"-only line ends the paragraph;
		// openers are read after the ">"; a lazy line continues the quoted paragraph.
		{"> a long\n> sentence.", []string{"a long\n> sentence."}, []BlockKind{P}},
		{"> One.\n> Two.", []string{"One.", "Two."}, []BlockKind{P}},
		{"> a\n>\n> b", []string{"a", "b"}, []BlockKind{P, P}},
		{"> x:\n> - y", []string{"x:", "y"}, []BlockKind{P, L}},
		{"> # h\n> body text.", []string{"# h", "body text."}, []BlockKind{H, P}},
		{"Text before.\n> quoted. Here.\nlazy line.", []string{"Text before.", "quoted.", "Here.\nlazy line."}, []BlockKind{P, P}},
	} {
		var got []string
		for _, sp := range Sentences(r.in) {
			got = append(got, r.in[sp[0]:sp[1]])
		}
		if !reflect.DeepEqual(got, r.want) {
			t.Errorf("Sentences(%q)\n got %q\nwant %q", r.in, got, r.want)
		}
		if r.kinds == nil {
			continue
		}
		var kinds []BlockKind
		for _, b := range Blocks(r.in) {
			kinds = append(kinds, b.Kind)
		}
		if !reflect.DeepEqual(kinds, r.kinds) {
			t.Errorf("Blocks(%q) kinds = %v, want %v", r.in, kinds, r.kinds)
		}
	}
}

// THE CORPUS SENTENCES STAY WHOLE. Each row is a block copied from a run's record — the render
// just after a gap's mint, or the final render for an anchor — with its newlines, and the whole
// sentence its gap quote or anchor stands in, held as a literal so the test shares no code with the
// splitter. The terminator clause keeps the seven fragment gaps whole ("50.8%", "9.54", "etc.)",
// "e.g.,", "verify_91.py", "numbers.education"); the block clause keeps b3's three gaps and the
// anchors in a soft-wrapped sentence whole. m8's row is the stated residue: a digit after a
// terminator joins two sentences.
func TestSentencesKeepsTheCorpusSentencesWhole(t *testing.T) {
	for _, r := range []struct {
		name, block string
		holds       [][2]string // a locator in the block, and the sentence holding its last byte
	}{
		{"quadratic-formula R2-2: the run has no render; this is edit 378's old span, the text as it stood, which begins mid-sentence", "of 127 prose units in v1 and 147 in v2, 64 are unchanged, so 50.8% of v1's prose survives verbatim<!--fx:f-fc114409--><!--proof:p-937be709-->; of the 62 v1 units absent from v2, 43 were edited and 19 deleted outright, and 39 v2 units are new.", [][2]string{{"survives verbatim", "of 127 prose units in v1 and 147 in v2, 64 are unchanged, so 50.8% of v1's prose survives verbatim<!--fx:f-fc114409--><!--proof:p-937be709-->; of the 62 v1 units absent from v2, 43 were edited and 19 deleted outright, and 39 v2 units are new."}}},
		{"universe2 G3", "**For 91:** √91 ≈ 9.54, so we test integers 2–9<!--fx:f-e92d24f4-->. The test succeeds: 91 mod 7 = 0, so 91 is composite.", [][2]string{{"integers 2–9", "**For 91:** √91 ≈ 9.54, so we test integers 2–9<!--fx:f-e92d24f4-->."}}},
		{"universe2 G14", "**For 91:** √91 ≈ 9.54, so we test all primes up to 9 (2, 3, 5, and 7)<!--fx:f-956f93c7--><!--fx:f-e92d24f4-->. Composite divisors need not be tested, since any composite number that divides 91 would itself have a prime factor that divides 91. The test succeeds: 91 mod 7 = 0, so 91 is composite.", [][2]string{{"5, and 7)", "**For 91:** √91 ≈ 9.54, so we test all primes up to 9 (2, 3, 5, and 7)<!--fx:f-956f93c7--><!--fx:f-e92d24f4-->."}}},
		{"universe-m12 G3", "- Test with other bases (a = 3, 5, 11, etc.) reinforces the conclusion<!--fx:f-ee5a6b64-->.", [][2]string{{"the conclusion", "Test with other bases (a = 3, 5, 11, etc.) reinforces the conclusion<!--fx:f-ee5a6b64-->."}}},
		{"b5 G6", "7. **What does it cost, and where would we stop?** The cost actually incurred was a handful of short computations and a small number of leaf-read reference lookups — minutes, not hours. The natural stopping point, reached here, is convergent agreement across independent computational methods and independent reference sources; going further (e.g., a full census of every Fermat/Miller–Rabin liar base, or a formal Lucas-test certificate) would add rigor appropriate to a much larger number, not to a two-digit one, and was explicitly declined for that reason<!--fx:f-32e7311b-->.", [][2]string{{"for that reason", "The natural stopping point, reached here, is convergent agreement across independent computational methods and independent reference sources; going further (e.g., a full census of every Fermat/Miller–Rabin liar base, or a formal Lucas-test certificate) would add rigor appropriate to a much larger number, not to a two-digit one, and was explicitly declined for that reason<!--fx:f-32e7311b-->."}}},
		{"b6 G5", "The standard bound for testing primality by trial division is the square root of the candidate: if 91 had no divisor at or below √91 ≈ 9.54, it could have none above it either, since any divisor above the root would need a co-divisor below it. That leaves four candidates to check — the primes 2, 3, 5, and 7. Dividing 91 by each: 91 ÷ 2 leaves remainder 1, 91 ÷ 3 leaves remainder 1, 91 ÷ 5 leaves remainder 1, and 91 ÷ 7 = 13 exactly. 91 has a prime divisor (7) at or below its square root, so by the trial-division bound it is composite: 91 = 7 × 13<!--proof:p-4e867682-->. (Recomputed directly: `scripts/verify_91.py`, testing every prime ≤ ⌊√91⌋ = 9 with no early termination.)<!--fx:f-719d69c4-->", [][2]string{{"no early termination.)", "(Recomputed directly: `scripts/verify_91.py`, testing every prime ≤ ⌊√91⌋ = 9 with no early termination.)<!--fx:f-719d69c4-->"}}},
		{"b7 G3", "4. **The case against.** The honest case against treating \"91 is composite\" as reliably established by any single method is real, and it has a name: 91 is documented as the smallest Fermat pseudoprime to base 3 — a single-base Fermat test using base 3 returns the exact residue a genuine prime would produce, and would report 91 as \"probably prime\" — a false verdict. Widening the census shows this is not an isolated quirk: 34 of the 88 possible bases (roughly 39%) fool the weaker Fermat test the same way. The Miller-Rabin refinement closes most of that gap but not all of it: exhaustive testing shows Miller-Rabin still returns a false \"probably prime\" result for 16 of the 88 bases (about 23% of the 70 bases actually coprime to 91), a residual that traces exactly to Euler's totient of 91. None of this changes the verdict, because trial division and the maintained sequence databases settle the question independently of any probabilistic test's base sensitivity — but it is a genuine reason not to trust a single-base Fermat or Miller-Rabin run on an arbitrary unfactored number of this kind, without either a deterministic bound on the bases needed or a corroborating direct-factorization method. A direct adversarial search across five reputable reference sources (Wikipedia, Cuemath, Vedantu, Smartick, numbers.education) turned up no source that disputes 91's compositeness or reports it as prime: the test-choice sensitivity above is the only genuine complication found, not a competing claim about the number itself<!--fx:f-3516bec3--><!--cite:c-b1abd4e2--><!--cite:c-8dd74d38--><!--cite:c-b3fdfad9--><!--cite:c-c3c245d9-->.", [][2]string{{"the number itself", "A direct adversarial search across five reputable reference sources (Wikipedia, Cuemath, Vedantu, Smartick, numbers.education) turned up no source that disputes 91's compositeness or reports it as prime: the test-choice sensitivity above is the only genuine complication found, not a competing claim about the number itself<!--fx:f-3516bec3--><!--cite:c-b1abd4e2--><!--cite:c-8dd74d38--><!--cite:c-b3fdfad9--><!--cite:c-c3c245d9-->."}}},
		{"b3 G1", "- **Deterministic Miller–Rabin**, with the witness set {2, 3, 5, 7} — proven to\n  correctly decide primality for every n < 3,215,031,751, so for n = 91 this is a\n  proof rather than a probabilistic result: composite<!--fx:f-811a6ab9-->.", [][2]string{{"result: composite", "**Deterministic Miller–Rabin**, with the witness set {2, 3, 5, 7} — proven to\n  correctly decide primality for every n < 3,215,031,751, so for n = 91 this is a\n  proof rather than a probabilistic result: composite<!--fx:f-811a6ab9-->."}}},
		{"b3 G2, b3 f-8be4bb71", "91 is not prime. It is composite, with complete factorization 91 = 7 × 13, both of\nwhich are themselves prime. This is settled with certainty — trial division to\n⌊√91⌋ = 9 is already a complete decision procedure for a number this size, and the\nresult is independently reproduced by five further, structurally unrelated methods\nwith zero disagreement among them<!--fx:f-8be4bb71-->. The sharpest caveat is not about the answer but\nabout how easy it is to get there the wrong way: a single-witness Fermat\nprimality check — a common quick heuristic — gives a false \"probably prime\" signal\nfor close to half of all bases coprime to 91 (35 of 72), including base 3 and base\n10, so a reader who runs one quick shortcut test at an unlucky base can walk away\nwith the wrong answer even though the question itself is not remotely close to\nbeing open.", [][2]string{{"disagreement among them", "This is settled with certainty — trial division to\n⌊√91⌋ = 9 is already a complete decision procedure for a number this size, and the\nresult is independently reproduced by five further, structurally unrelated methods\nwith zero disagreement among them<!--fx:f-8be4bb71-->."}, {"<!--fx:f-8be4bb71-->", "This is settled with certainty — trial division to\n⌊√91⌋ = 9 is already a complete decision procedure for a number this size, and the\nresult is independently reproduced by five further, structurally unrelated methods\nwith zero disagreement among them<!--fx:f-8be4bb71-->."}}},
		{"b3 G3", "- Were the two HTTP 403 responses (OEIS's composites-sequence alternate path and a\n  numbers-reference site) an artifact of the fetching environment specifically, or\n  would the same sources fail from any fetch context? Not distinguished here<!--fx:f-f03e68d7-->.", [][2]string{{"Not distinguished here", "Not distinguished here<!--fx:f-f03e68d7-->."}}},
		{"b3 p-6844d749", "Trial division tests every integer d from 2 through ⌊√91⌋ = 9, since any factor\npair of a composite n must have one member at or below √n, making this range both\nnecessary and sufficient to decide primality for a specific integer this size. Only\nd = 7 divides 91 evenly, with quotient 13, and 7 × 13 = 91<!--proof:p-6844d749-->. Both cofactors are\nthemselves prime: 7 has no divisor in [2, ⌊√7⌋ = 2], and 13 has no divisor in\n[2, ⌊√13⌋ = 3]. So 7 × 13 is 91's complete prime factorization — the full\ndecomposition, not merely one divisor found among several possible.", [][2]string{{"<!--proof:p-6844d749-->", "Only\nd = 7 divides 91 evenly, with quotient 13, and 7 × 13 = 91<!--proof:p-6844d749-->."}}},
		{"b3 p-bd21ef70", "An unbounded brute-force divisor sweep over the full range [1, 91], rather than one\nthat assumes the √n shortcut, finds exactly the four divisors {1, 7, 13, 91}; each\ndivisor at or below the √91 bound pairs with a divisor above it via n/d (1 with 91,\n7 with 13), directly confirming rather than merely assuming the pairing property\nthe shortcut depends on for this particular n<!--proof:p-bd21ef70-->.", [][2]string{{"<!--proof:p-bd21ef70-->", "An unbounded brute-force divisor sweep over the full range [1, 91], rather than one\nthat assumes the √n shortcut, finds exactly the four divisors {1, 7, 13, 91}; each\ndivisor at or below the √91 bound pairs with a divisor above it via n/d (1 with 91,\n7 with 13), directly confirming rather than merely assuming the pairing property\nthe shortcut depends on for this particular n<!--proof:p-bd21ef70-->."}}},
		{"b3 p-e2c14426", "- **Wilson's theorem.** For a prime p, (p−1)! ≡ −1 (mod p); for a composite n > 4,\n  (n−1)! ≡ 0 (mod n), because every factor of n appears with multiplicity among\n  1..n−1 and so divides the product. Computed via an iterative modular product\n  (avoiding both the ~140-digit exact factorial and any floating-point precision\n  loss): 90! mod 91 = 0, not 90 (≡ −1 mod 91) — the composite signature<!--proof:p-e2c14426-->. Since\n  91 = 7 × 13 and both 7 and 13 are ≤ 90, both appear as factors in 1×2×...×90, so\n  the product is divisible by 91. This test evaluates a global algebraic identity\n  rather than testing divisors of 91 at all, so its agreement with trial division is\n  real corroboration, not the same check run twice.", [][2]string{{"<!--proof:p-e2c14426-->", "Computed via an iterative modular product\n  (avoiding both the ~140-digit exact factorial and any floating-point precision\n  loss): 90! mod 91 = 0, not 90 (≡ −1 mod 91) — the composite signature<!--proof:p-e2c14426-->."}}},
		{"b3 p-d6107488, b3 f-811a6ab9", "- **Deterministic Miller–Rabin**, with the witness set {2, 3, 5, 7} — proven to\n  correctly decide primality for every n < 3,215,031,751. Run as the genuine\n  witness-exponentiation test, with no small-prime divisibility pre-check ahead\n  of it: n − 1 = 90 = 45 × 2¹ (d = 45, r = 1); for every witness a ∈ {2, 3, 5, 7},\n  a^d mod 91 lands outside {1, 90} — 2^45 ≡ 57, 3^45 ≡ 27, 5^45 ≡ 83, 7^45 ≡ 21\n  (mod 91)<!--proof:p-d6107488--> — so each witness independently proves compositeness by the\n  Miller–Rabin criterion (witness a = 7 happens to divide 91, so that one\n  witness's result is not independent of the divisibility fact trial division\n  already found; witnesses 2, 3 and 5 are genuinely coprime to 91 and carry the\n  corroboration on their own): composite<!--fx:f-811a6ab9-->.", [][2]string{{"<!--proof:p-d6107488-->", "Run as the genuine\n  witness-exponentiation test, with no small-prime divisibility pre-check ahead\n  of it: n − 1 = 90 = 45 × 2¹ (d = 45, r = 1); for every witness a ∈ {2, 3, 5, 7},\n  a^d mod 91 lands outside {1, 90} — 2^45 ≡ 57, 3^45 ≡ 27, 5^45 ≡ 83, 7^45 ≡ 21\n  (mod 91)<!--proof:p-d6107488--> — so each witness independently proves compositeness by the\n  Miller–Rabin criterion (witness a = 7 happens to divide 91, so that one\n  witness's result is not independent of the divisibility fact trial division\n  already found; witnesses 2, 3 and 5 are genuinely coprime to 91 and carry the\n  corroboration on their own): composite<!--fx:f-811a6ab9-->."}, {"<!--fx:f-811a6ab9-->", "Run as the genuine\n  witness-exponentiation test, with no small-prime divisibility pre-check ahead\n  of it: n − 1 = 90 = 45 × 2¹ (d = 45, r = 1); for every witness a ∈ {2, 3, 5, 7},\n  a^d mod 91 lands outside {1, 90} — 2^45 ≡ 57, 3^45 ≡ 27, 5^45 ≡ 83, 7^45 ≡ 21\n  (mod 91)<!--proof:p-d6107488--> — so each witness independently proves compositeness by the\n  Miller–Rabin criterion (witness a = 7 happens to divide 91, so that one\n  witness's result is not independent of the divisibility fact trial division\n  already found; witnesses 2, 3 and 5 are genuinely coprime to 91 and carry the\n  corroboration on their own): composite<!--fx:f-811a6ab9-->."}}},
		{"b3 p-a897c923", "- **Fermat's factorization method** (difference of squares: n = a² − b² =\n  (a−b)(a+b)). Searching for a square minus 91 that is itself a perfect square\n  converges on the first candidate: a = 10 gives 10² − 91 = 9 = 3², so\n  91 = 10² − 3² = (10 − 3)(10 + 3) = 7 × 13<!--proof:p-a897c923--> — independently reproducing both\n  compositeness and the exact factor pair by a method structurally unlike direct\n  division.", [][2]string{{"<!--proof:p-a897c923-->", "Searching for a square minus 91 that is itself a perfect square\n  converges on the first candidate: a = 10 gives 10² − 91 = 9 = 3², so\n  91 = 10² − 3² = (10 − 3)(10 + 3) = 7 × 13<!--proof:p-a897c923--> — independently reproducing both\n  compositeness and the exact factor pair by a method structurally unlike direct\n  division."}}},
		{"b3 p-8f09d8a4", "- **Sieve of Eratosthenes** over [2, 100] — elimination by multiples across a whole\n  neighborhood rather than testing 91 in isolation. 91 is left unmarked\n  (composite), and the sieve's own resulting prime list gives 89 and 97 as 91's\n  immediate prime neighbors<!--proof:p-8f09d8a4-->.", [][2]string{{"<!--proof:p-8f09d8a4-->", "**Sieve of Eratosthenes** over [2, 100] — elimination by multiples across a whole\n  neighborhood rather than testing 91 in isolation. 91 is left unmarked\n  (composite), and the sieve's own resulting prime list gives 89 and 97 as 91's\n  immediate prime neighbors<!--proof:p-8f09d8a4-->."}}},
		{"b3 p-c5213636, b3 c-2e118c62, b3 c-ecf4fa0a", "A single-witness Fermat test (from Fermat's little theorem: for a prime p and\ngcd(a,p) = 1, a^(p−1) ≡ 1 mod p) is a common quick primality heuristic. For 91\nspecifically, base 2 correctly detects compositeness: 2^90 mod 91 = 64, not 1<!--proof:p-c5213636-->. But\nthe identical test at base 3 or base 10 gives a false \"probably prime\" signal:\n3^90 mod 91 = 1 and 10^90 mod 91 = 1. This is exactly the base-3 and base-10\nFermat-pseudoprime phenomenon: 91 is the first listed term of the On-Line\nEncyclopedia of Integer Sequences' \"Pseudoprimes to base 3\" sequence (91, 121, 286,\n671, 703, 949, 1105, …)<!--cite:c-2e118c62-->, and the third listed term of its \"Pseudoprimes to base 10\"\nsequence (9, 33, 91, 99, 259, 451, …)<!--cite:c-ecf4fa0a-->.", [][2]string{{"<!--proof:p-c5213636-->", "For 91\nspecifically, base 2 correctly detects compositeness: 2^90 mod 91 = 64, not 1<!--proof:p-c5213636-->."}, {"<!--cite:c-2e118c62-->", "This is exactly the base-3 and base-10\nFermat-pseudoprime phenomenon: 91 is the first listed term of the On-Line\nEncyclopedia of Integer Sequences' \"Pseudoprimes to base 3\" sequence (91, 121, 286,\n671, 703, 949, 1105, …)<!--cite:c-2e118c62-->, and the third listed term of its \"Pseudoprimes to base 10\"\nsequence (9, 33, 91, 99, 259, 451, …)<!--cite:c-ecf4fa0a-->."}, {"<!--cite:c-ecf4fa0a-->", "This is exactly the base-3 and base-10\nFermat-pseudoprime phenomenon: 91 is the first listed term of the On-Line\nEncyclopedia of Integer Sequences' \"Pseudoprimes to base 3\" sequence (91, 121, 286,\n671, 703, 949, 1105, …)<!--cite:c-2e118c62-->, and the third listed term of its \"Pseudoprimes to base 10\"\nsequence (9, 33, 91, 99, 259, 451, …)<!--cite:c-ecf4fa0a-->."}}},
		{"b3 p-a30013b5", "A full sweep of every base a in [2, 90] with gcd(a, 91) = 1 — there are\nφ(91) = (7−1)(13−1) = 72 such bases — finds that 35 of the 72, about 48.6%, satisfy\na^90 ≡ 1 (mod 91)<!--proof:p-a30013b5-->, i.e. would wrongly pass a one-shot Fermat check. A randomly\nchosen coprime base therefore has close to an even chance of misleadingly\nsuggesting 91 is prime under that single check alone. Because 35 is strictly less\nthan 72, at least one coprime base — including 2 — correctly fails the test, so by\ndefinition 91 is not a Carmichael number: a Carmichael number must fool every base\ncoprime to it, not merely a large minority of them. This near-50% fooling rate is\nthe concrete reason \"is 91 prime?\" is a fair, non-trivial question to ask rather\nthan something obviously settled by inspection: a reader who runs a single Fermat\ncheck at an unlucky base is left with the wrong answer, even though trial division,\nWilson's theorem, or Miller–Rabin with an established witness set settles the\nquestion immediately and completely.", [][2]string{{"<!--proof:p-a30013b5-->", "A full sweep of every base a in [2, 90] with gcd(a, 91) = 1 — there are\nφ(91) = (7−1)(13−1) = 72 such bases — finds that 35 of the 72, about 48.6%, satisfy\na^90 ≡ 1 (mod 91)<!--proof:p-a30013b5-->, i.e. would wrongly pass a one-shot Fermat check."}}},
		{"b3 c-5eabefc8", "The On-Line Encyclopedia of Integer Sequences' sequence of prime numbers (A000040)\nlists its terms directly as \"...79, 83, 89, 97, 101, 103...\" — 91 does not appear\nbetween 89 and 97, consistent with compositeness<!--cite:c-5eabefc8-->.", [][2]string{{"<!--cite:c-5eabefc8-->", "The On-Line Encyclopedia of Integer Sequences' sequence of prime numbers (A000040)\nlists its terms directly as \"...79, 83, 89, 97, 101, 103...\" — 91 does not appear\nbetween 89 and 97, consistent with compositeness<!--cite:c-5eabefc8-->."}}},
		{"b3 c-8cde8cc2", "The Encyclopedia's sequence of composite numbers (A002808) would be the single most\ndirectly on-point external reference, but its fetched landing page's rendered term\nlist truncates at 88 terms before reaching 91; citing this page for 91's membership\nwithout following the sequence's b-file would overclaim what was actually read, so\nit is not used here as direct evidence for 91 specifically<!--cite:c-8cde8cc2--> — the compositeness\nclaim instead rests on the redundant, directly leaf-read sources below, each of\nwhich by construction lists only composite numbers or states the factorization\noutright.", [][2]string{{"<!--cite:c-8cde8cc2-->", "The Encyclopedia's sequence of composite numbers (A002808) would be the single most\ndirectly on-point external reference, but its fetched landing page's rendered term\nlist truncates at 88 terms before reaching 91; citing this page for 91's membership\nwithout following the sequence's b-file would overclaim what was actually read, so\nit is not used here as direct evidence for 91 specifically<!--cite:c-8cde8cc2--> — the compositeness\nclaim instead rests on the redundant, directly leaf-read sources below, each of\nwhich by construction lists only composite numbers or states the factorization\noutright."}}},
		{"b3 c-38bea55a", "Wikipedia's \"91 (number)\" article states in its infobox that the Factorization is\n\"7 × 13\" and the Divisors are \"1, 7, 13, 91,\" matching the computed factorization\nexactly, and calls 91 \"the twenty-seventh distinct semiprime<!--cite:c-38bea55a-->\" — consistent with 91\nhaving exactly two prime factors counted with multiplicity.", [][2]string{{"<!--cite:c-38bea55a-->", "Wikipedia's \"91 (number)\" article states in its infobox that the Factorization is\n\"7 × 13\" and the Divisors are \"1, 7, 13, 91,\" matching the computed factorization\nexactly, and calls 91 \"the twenty-seventh distinct semiprime<!--cite:c-38bea55a-->\" — consistent with 91\nhaving exactly two prime factors counted with multiplicity."}}},
		{"b3 c-f733bc64", "Cuemath's \"Is 91 a Prime Number?\" page states directly: \"Factors of 91: 1, 7, 13,\n91\" and \"Since 91 has more than 2 factors, we can say that 91 is not a prime\nnumber<!--cite:c-f733bc64-->\" — matching the computed factorization and conclusion exactly.", [][2]string{{"<!--cite:c-f733bc64-->", "Cuemath's \"Is 91 a Prime Number?\" page states directly: \"Factors of 91: 1, 7, 13,\n91\" and \"Since 91 has more than 2 factors, we can say that 91 is not a prime\nnumber<!--cite:c-f733bc64-->\" — matching the computed factorization and conclusion exactly."}}},
		{"b3 c-91b91a86", "Wikipedia's article also carries the claim that 91 is \"the smallest number that\nlooks prime but is not, proven using the Rotten Theorem by John Conway,\" cited\nthere to two informal web sources — a YouTube video (\"John Conway proves that 91 is\nthe smallest number which looks prime but isn't,\" Ryan Andersen, 31 December 2020)\nand a blog tag-listing page (\"Prime Numbers,\" The Aperiodical, 9 May 2024)<!--cite:c-91b91a86--> — neither\na paper nor a standard number-theory reference, and \"Rotten Theorem\" does not\ncorrespond to any established named result found in this search. This is retained\nonly as color explaining why 91 is a commonly cited \"trap\" number, not as evidence\nfor the compositeness claim, which is independently and redundantly established\nabove.", [][2]string{{"<!--cite:c-91b91a86-->", "Wikipedia's article also carries the claim that 91 is \"the smallest number that\nlooks prime but is not, proven using the Rotten Theorem by John Conway,\" cited\nthere to two informal web sources — a YouTube video (\"John Conway proves that 91 is\nthe smallest number which looks prime but isn't,\" Ryan Andersen, 31 December 2020)\nand a blog tag-listing page (\"Prime Numbers,\" The Aperiodical, 9 May 2024)<!--cite:c-91b91a86--> — neither\na paper nor a standard number-theory reference, and \"Rotten Theorem\" does not\ncorrespond to any established named result found in this search."}}},
		{"b3 f-950a7234", "- Would OEIS A002808's b-file (rather than its truncated default landing page)\n  directly list 91? Closing that specific citation gap is optional, since the\n  claim is already redundantly supported elsewhere<!--fx:f-950a7234-->.", [][2]string{{"<!--fx:f-950a7234-->", "Closing that specific citation gap is optional, since the\n  claim is already redundantly supported elsewhere<!--fx:f-950a7234-->."}}},
		{"universe-m14 c-1b559e10", "Authoritative modern sources consistently enumerate the 25 primes from 1 to 100<!--cite:c-1b559e10-->:\n2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97.", [][2]string{{"<!--cite:c-1b559e10-->", "Authoritative modern sources consistently enumerate the 25 primes from 1 to 100<!--cite:c-1b559e10-->:\n2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97."}}},
		{"universe-m8 f-7af4335b", "- Base 2: Compute 2^90 mod 91 (verified by reproducible computation).\n  2^90 ≡ 64 (mod 91) ≢ 1 (mod 91)<!--fx:f-7af4335b-->.\n  Therefore, 2 is a Fermat witness, proving 91 composite with certainty<!--proof:p-0e217cfb--><!--proof:p-19ec92da--><!--fx:f-904d9543-->.", [][2]string{{"<!--fx:f-7af4335b-->", "Base 2: Compute 2^90 mod 91 (verified by reproducible computation).\n  2^90 ≡ 64 (mod 91) ≢ 1 (mod 91)<!--fx:f-7af4335b-->."}}},
	} {
		for _, h := range r.holds {
			at := strings.Index(r.block, h[0]) + len(h[0]) - 1
			got := ""
			for _, sp := range Sentences(r.block) {
				if sp[0] <= at && at < sp[1] {
					got = r.block[sp[0]:sp[1]]
				}
			}
			if got != h[1] {
				t.Errorf("%s, at %q:\n got %q\nwant %q", r.name, h[0], got, h[1])
			}
		}
	}
}
