package main

import (
	"encoding/json"
	"strings"
	"testing"
)

func guardCmd(bin, ev string) string {
	return `B="${CLAUDE_PLUGIN_ROOT}/bin/` + bin + `"; if [ -x "$B" ] || [ -x "$B.exe" ]; then exec "$B"; fi; ` +
		`F="${CLAUDE_PLUGIN_ROOT}/hooks/fetch-bin.sh"; if [ -f "$F" ]; then exec sh "$F" hook ` + ev + `; fi; echo x >&2`
}

func hooksDoc(t *testing.T, ev, cmd string) []byte {
	t.Helper()
	b, err := json.Marshal(map[string]any{"hooks": map[string]any{
		ev: []any{map[string]any{"hooks": []any{map[string]any{"type": "command", "command": cmd}}}},
	}})
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func TestAGuardNamingItsOwnEventPasses(t *testing.T) {
	if got := guardProblems("p", hooksDoc(t, "PreToolUse", guardCmd("x", "PreToolUse"))); len(got) != 0 {
		t.Fatalf("a correct guard was reported: %v", got)
	}
}

// The literal decides whether fetch-bin.sh may speak, so a guard carrying another event's name
// must fail — this is the slip the check exists for.
func TestAGuardNamingAnotherEventFails(t *testing.T) {
	got := guardProblems("p", hooksDoc(t, "SubagentStop", guardCmd("x", "Stop")))
	if len(got) != 1 || !strings.Contains(got[0], "SubagentStop") {
		t.Fatalf("want one problem naming SubagentStop, got %v", got)
	}
}

// A prefix of the right event is still the wrong event.
func TestAnEventPrefixIsNotTheEvent(t *testing.T) {
	got := guardProblems("p", hooksDoc(t, "PostToolUseFailure", guardCmd("x", "PostToolUse")))
	if len(got) != 1 {
		t.Fatalf("PostToolUse under PostToolUseFailure must fail, got %v", got)
	}
}

func TestAGuardThatSkipsFetchBinFails(t *testing.T) {
	cmd := `B="${CLAUDE_PLUGIN_ROOT}/bin/x"; if [ -x "$B" ]; then exec "$B"; fi; echo missing >&2`
	got := guardProblems("p", hooksDoc(t, "Stop", cmd))
	if len(got) != 1 || !strings.Contains(got[0], "does not hand") {
		t.Fatalf("want the does-not-hand problem, got %v", got)
	}
}

func TestNoGuardAtAllIsLoud(t *testing.T) {
	got := guardProblems("p", hooksDoc(t, "Stop", "echo not a guard"))
	if len(got) != 1 || !strings.Contains(got[0], "no guard found") {
		t.Fatalf("want the no-guard problem, got %v", got)
	}
}

func TestUnparseableHooksJSONIsReported(t *testing.T) {
	if got := guardProblems("p", []byte("{")); len(got) != 1 || !strings.Contains(got[0], "does not parse") {
		t.Fatalf("want a parse problem, got %v", got)
	}
}

func TestRenderMarksTheCopyGenerated(t *testing.T) {
	out := string(render([]byte("echo hi\n")))
	if !strings.HasPrefix(out, "# Code generated by scripts/fetchbingen from "+src+". DO NOT EDIT.\n") || !strings.HasSuffix(out, "echo hi\n") {
		t.Fatalf("unexpected render: %q", out)
	}
}
