// Command fetchbingen writes the one authored fetch-bin.sh into every plugin that ships hook
// binaries, and checks that every hook guard hands a missing binary to it under its own event.
//
// Dev tooling for this repository only. What ships is the copies it writes.
//
// # Why copies
//
// An install carries only that plugin's tree, so a guard can reach no other plugin's files: each
// plugin with binaries needs its own fetch-bin.sh. The copies are generated from
// scripts/fetchbingen/fetch-bin.sh so the fetch contract is stated once; -check fails on drift.
//
// # Why the guards are checked here
//
// Each guard passes its event name to fetch-bin.sh as a literal, and that literal is a copy of
// the hooks.json key it sits under. fetch-bin.sh decides from it whether a message can reach the
// human, so a copy-paste slip would silently move a guard in or out of the displaying set.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ctoforaday/special-circumstances/scripts/internal/gitx"
)

// src is the authored script.
const src = "scripts/fetchbingen/fetch-bin.sh"

// fetchVar is how a guard names its plugin's fetch-bin.sh.
const fetchVar = `F="${CLAUDE_PLUGIN_ROOT}/hooks/fetch-bin.sh"`

func main() {
	check := flag.Bool("check", false, "verify every copy and every guard instead of writing the copies")
	flag.Parse()

	root, err := gitx.Root()
	if err != nil {
		fmt.Fprintln(os.Stderr, "fetchbingen:", err)
		os.Exit(1)
	}
	body, err := os.ReadFile(filepath.Join(root, src))
	if err != nil {
		fmt.Fprintln(os.Stderr, "fetchbingen:", err)
		os.Exit(1)
	}
	want := render(body)
	plugins, err := targets(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "fetchbingen:", err)
		os.Exit(1)
	}

	var problems []string
	for _, p := range plugins {
		dst := filepath.Join(root, "plugins", p, "hooks", "fetch-bin.sh")
		if !*check {
			if err := os.WriteFile(dst, want, 0o644); err != nil {
				fmt.Fprintln(os.Stderr, "fetchbingen:", err)
				os.Exit(1)
			}
			continue
		}
		got, err := os.ReadFile(dst)
		switch {
		case err != nil:
			problems = append(problems, fmt.Sprintf("plugins/%s/hooks/fetch-bin.sh is missing (%v)", p, err))
		case !bytes.Equal(got, want):
			problems = append(problems, fmt.Sprintf("plugins/%s/hooks/fetch-bin.sh has drifted from %s", p, src))
		}
		// bin/ must exist when the plugin is enabled: Claude Code puts it on the Bash PATH then or
		// never, and a directory the fetcher creates later in the session is not added.
		if _, err := os.Stat(filepath.Join(root, "plugins", p, "bin", ".gitkeep")); err != nil {
			problems = append(problems, fmt.Sprintf("plugins/%s ships binaries but has no bin/.gitkeep, so a fresh install has no bin/ to put on PATH", p))
		}
		hj, err := os.ReadFile(filepath.Join(root, "plugins", p, "hooks", "hooks.json"))
		if err != nil {
			problems = append(problems, fmt.Sprintf("plugins/%s ships binaries but its hooks/hooks.json cannot be read: %v", p, err))
			continue
		}
		problems = append(problems, guardProblems(p, hj)...)
	}

	if !*check {
		fmt.Printf("fetchbingen: wrote fetch-bin.sh into %d plugin(s): %s\n", len(plugins), strings.Join(plugins, ", "))
		return
	}
	if len(problems) > 0 {
		for _, s := range problems {
			fmt.Fprintln(os.Stderr, "fetchbingen:", s)
		}
		fmt.Fprintf(os.Stderr, "fetchbingen: edit %s and run `go -C scripts run ./fetchbingen`; a guard's event literal must be the key it sits under.\n", src)
		os.Exit(1)
	}
	fmt.Printf("fetchbingen: %d plugin(s) match %s, and every guard names its own event\n", len(plugins), src)
}

// render is the generated form of the authored script.
func render(body []byte) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# Code generated by scripts/fetchbingen from %s. DO NOT EDIT.\n", src)
	b.Write(body)
	return b.Bytes()
}

// targets lists the plugins that ship binaries: those with a tools/cmd directory, the predicate
// the release job and the doctor use.
func targets(root string) ([]string, error) {
	entries, err := os.ReadDir(filepath.Join(root, "plugins"))
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if st, err := os.Stat(filepath.Join(root, "plugins", e.Name(), "tools", "cmd")); err == nil && st.IsDir() {
			out = append(out, e.Name())
		}
	}
	// A plugins/ that yields no target would write nothing and check nothing, and say so as success.
	if len(out) == 0 {
		return nil, fmt.Errorf("no plugin under plugins/ has tools/cmd — refusing to generate nothing")
	}
	sort.Strings(out)
	return out, nil
}

// guardProblems reports every guard in one plugin's hooks.json that does not hand a missing
// binary to fetch-bin.sh under the event key it sits under. A guard is a command that runs a
// binary from ${CLAUDE_PLUGIN_ROOT}/bin/.
func guardProblems(plugin string, data []byte) []string {
	var doc struct {
		Hooks map[string][]struct {
			Hooks []struct {
				Command string `json:"command"`
			} `json:"hooks"`
		} `json:"hooks"`
	}
	if err := json.Unmarshal(data, &doc); err != nil {
		return []string{fmt.Sprintf("plugins/%s/hooks/hooks.json does not parse: %v", plugin, err)}
	}
	events := make([]string, 0, len(doc.Hooks))
	for ev := range doc.Hooks {
		events = append(events, ev)
	}
	sort.Strings(events)

	var out []string
	guards := 0
	for _, ev := range events {
		for _, entry := range doc.Hooks[ev] {
			for _, h := range entry.Hooks {
				if !strings.Contains(h.Command, "${CLAUDE_PLUGIN_ROOT}/bin/") {
					continue
				}
				guards++
				if !strings.Contains(h.Command, fetchVar) {
					out = append(out, fmt.Sprintf("plugins/%s: a %s guard does not hand a missing binary to fetch-bin.sh", plugin, ev))
					continue
				}
				if !strings.Contains(h.Command, `exec sh "$F" hook `+ev+`;`) {
					out = append(out, fmt.Sprintf("plugins/%s: a %s guard passes fetch-bin.sh an event other than %s", plugin, ev, ev))
				}
			}
		}
	}
	// Zero guards in a plugin that ships binaries means the pattern moved, not that all is well.
	if guards == 0 {
		out = append(out, fmt.Sprintf("plugins/%s: no guard found in hooks.json — the shape this check reads has moved, so it would pass without reading anything", plugin))
	}
	return out
}
