// Command fetchbingen writes the one authored fetch-bin.sh into every plugin that ships hook
// binaries, and checks that every hook guard hands a missing binary to it under its own event.
//
// Dev tooling for this repository only. What ships is the copies it writes.
//
// # Why copies
//
// An install carries only that plugin's tree, so a guard can reach no other plugin's files: each
// plugin with binaries needs its own fetch-bin.sh. The copies are generated from
// scripts/fetchbingen/fetch-bin.sh so the fetch contract is stated once; -check fails on drift.
//
// # Why the guards are checked here
//
// Each guard passes its event name to fetch-bin.sh as a literal, and that literal is a copy of
// the hooks.json key it sits under. fetch-bin.sh decides from it whether a message can reach the
// human, so a copy-paste slip would silently move a guard in or out of the displaying set.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ctoforaday/special-circumstances/scripts/internal/gitx"
)

// src is the authored script.
const src = "scripts/fetchbingen/fetch-bin.sh"

// fetchVar is how a guard names its plugin's fetch-bin.sh.
const fetchVar = `F="${CLAUDE_PLUGIN_ROOT}/hooks/fetch-bin.sh"`

// ensureEntry is the SessionStart entry that asks the version question once per session. A guard
// fires only when its binary is ABSENT, so without this a binary from an older release is treated
// as current for as long as it sits there. It checks its script exists before running it for the
// reason every guard checks its binary: a bare path to something missing fails the event.
// prosthetic-conscience's hookinvocation test admits exactly this command as the one hooks.json
// entry that runs no binary, so the two must stay the same string.
const ensureEntry = `F="${CLAUDE_PLUGIN_ROOT}/hooks/fetch-bin.sh"; if [ -f "$F" ]; then exec sh "$F" ensure SessionStart; fi`

func main() {
	check := flag.Bool("check", false, "verify every copy and every guard instead of writing the copies")
	flag.Parse()

	root, err := gitx.Root()
	if err != nil {
		fmt.Fprintln(os.Stderr, "fetchbingen:", err)
		os.Exit(1)
	}
	body, err := os.ReadFile(filepath.Join(root, src))
	if err != nil {
		fmt.Fprintln(os.Stderr, "fetchbingen:", err)
		os.Exit(1)
	}
	want := render(body)
	plugins, err := targets(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "fetchbingen:", err)
		os.Exit(1)
	}

	var problems []string
	for _, p := range plugins {
		dst := filepath.Join(root, "plugins", p, "hooks", "fetch-bin.sh")
		if !*check {
			if err := os.WriteFile(dst, want, 0o644); err != nil {
				fmt.Fprintln(os.Stderr, "fetchbingen:", err)
				os.Exit(1)
			}
			continue
		}
		got, err := os.ReadFile(dst)
		switch {
		case err != nil:
			problems = append(problems, fmt.Sprintf("plugins/%s/hooks/fetch-bin.sh is missing (%v)", p, err))
		case !bytes.Equal(got, want):
			problems = append(problems, fmt.Sprintf("plugins/%s/hooks/fetch-bin.sh has drifted from %s", p, src))
		}
		// bin/ must exist when the plugin is enabled: Claude Code puts it on the Bash PATH then or
		// never, and a directory the fetcher creates later in the session is not added.
		if _, err := os.Stat(filepath.Join(root, "plugins", p, "bin", ".gitkeep")); err != nil {
			problems = append(problems, fmt.Sprintf("plugins/%s ships binaries but has no bin/.gitkeep, so a fresh install has no bin/ to put on PATH", p))
		}
		hj, err := os.ReadFile(filepath.Join(root, "plugins", p, "hooks", "hooks.json"))
		if err != nil {
			problems = append(problems, fmt.Sprintf("plugins/%s ships binaries but its hooks/hooks.json cannot be read: %v", p, err))
			continue
		}
		problems = append(problems, guardProblems(p, hj)...)
	}
	problems = append(problems, ensureCopyProblems(root)...)

	if !*check {
		fmt.Printf("fetchbingen: wrote fetch-bin.sh into %d plugin(s): %s\n", len(plugins), strings.Join(plugins, ", "))
		return
	}
	if len(problems) > 0 {
		for _, s := range problems {
			fmt.Fprintln(os.Stderr, "fetchbingen:", s)
		}
		fmt.Fprintf(os.Stderr, "fetchbingen: edit %s and run `go -C scripts run ./fetchbingen`; a guard's event literal must be the key it sits under.\n", src)
		os.Exit(1)
	}
	fmt.Printf("fetchbingen: %d plugin(s) match %s, and every guard names its own event\n", len(plugins), src)
}

// render is the generated form of the authored script.
func render(body []byte) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# Code generated by scripts/fetchbingen from %s. DO NOT EDIT.\n", src)
	b.Write(body)
	return b.Bytes()
}

// targets lists the plugins that ship binaries: those with a tools/cmd directory, the predicate
// the release job and the doctor use.
func targets(root string) ([]string, error) {
	entries, err := os.ReadDir(filepath.Join(root, "plugins"))
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if st, err := os.Stat(filepath.Join(root, "plugins", e.Name(), "tools", "cmd")); err == nil && st.IsDir() {
			out = append(out, e.Name())
		}
	}
	// A plugins/ that yields no target would write nothing and check nothing, and say so as success.
	if len(out) == 0 {
		return nil, fmt.Errorf("no plugin under plugins/ has tools/cmd — refusing to generate nothing")
	}
	sort.Strings(out)
	return out, nil
}

// guardProblems reports every guard in one plugin's hooks.json that does not hand a missing
// binary to fetch-bin.sh under the event key it sits under. A guard is a command that runs a
// binary from ${CLAUDE_PLUGIN_ROOT}/bin/.
func guardProblems(plugin string, data []byte) []string {
	var doc struct {
		Hooks map[string][]struct {
			Hooks []struct {
				Command string `json:"command"`
			} `json:"hooks"`
		} `json:"hooks"`
	}
	if err := json.Unmarshal(data, &doc); err != nil {
		return []string{fmt.Sprintf("plugins/%s/hooks/hooks.json does not parse: %v", plugin, err)}
	}
	events := make([]string, 0, len(doc.Hooks))
	for ev := range doc.Hooks {
		events = append(events, ev)
	}
	sort.Strings(events)

	var out []string
	guards, ensures := 0, 0
	for _, ev := range events {
		for _, entry := range doc.Hooks[ev] {
			for _, h := range entry.Hooks {
				if ev == "SessionStart" && h.Command == ensureEntry {
					ensures++
					continue
				}
				if !strings.Contains(h.Command, "${CLAUDE_PLUGIN_ROOT}/bin/") {
					continue
				}
				guards++
				if !strings.Contains(h.Command, fetchVar) {
					out = append(out, fmt.Sprintf("plugins/%s: a %s guard does not hand a missing binary to fetch-bin.sh", plugin, ev))
					continue
				}
				if !strings.Contains(h.Command, `exec sh "$F" hook `+ev+`;`) {
					out = append(out, fmt.Sprintf("plugins/%s: a %s guard passes fetch-bin.sh an event other than %s", plugin, ev, ev))
				}
			}
		}
	}
	// The version question is asked once per session, from SessionStart. A plugin without this
	// entry heals only when a binary is missing outright, which is the state frank-exchange-of-views
	// was in: three guards, no SessionStart hook at all, and a stale binary would have stayed.
	if ensures != 1 {
		out = append(out, fmt.Sprintf("plugins/%s: wants exactly one SessionStart entry running `fetch-bin.sh ensure SessionStart`, found %d", plugin, ensures))
	}
	// Zero guards in a plugin that ships binaries means the pattern moved, not that all is well.
	if guards == 0 {
		out = append(out, fmt.Sprintf("plugins/%s: no guard found in hooks.json — the shape this check reads has moved, so it would pass without reading anything", plugin))
	}
	return out
}

// ensureCopies are the tests that admit the ensure entry by its exact string. They sit in plugin
// modules that cannot import this one, so the string is copied rather than shared, and a copy that
// drifts rejects the shipped entry. frank-exchange-of-views' copy runs only under
// FEOV_RELEASE_GATE=1: when #980 added the entry without it, no PR gate noticed and the 1.69.0 tag's
// release run failed on it. This check runs everywhere.
var ensureCopies = []string{
	"plugins/prosthetic-conscience/tools/internal/hookinvocation/invocation_test.go",
	"plugins/frank-exchange-of-views/tools/releasegate/fuzz/hookinvocation_test.go",
}

func ensureCopyProblems(root string) []string {
	var out []string
	for _, rel := range ensureCopies {
		b, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			out = append(out, fmt.Sprintf("%s cannot be read, so its copy of the ensure entry is unchecked: %v", rel, err))
			continue
		}
		if !bytes.Contains(b, []byte(ensureEntry)) {
			out = append(out, fmt.Sprintf("%s does not carry the exact ensure entry, so it rejects what every plugin ships", rel))
		}
	}
	return out
}
