package setup

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/ctoforaday/special-circumstances/plugins/frank-exchange-of-views/tools/internal/record"
	"github.com/ctoforaday/special-circumstances/plugins/frank-exchange-of-views/tools/internal/seatenv"
)

// THE DISPATCHER BAKES THE RUN IN; THE SEAT EXECUTES A PATH INSTEAD OF RETYPING A VALUE.
//
// The engine already TELLS every seat its run — `runDir` appears seventeen times in the
// dispatch prompts. Supplying the fact was never the gap. The gap is that a fact a seat
// RETYPES is one nothing can refuse: ten of the first live run's fifty-five tool-call errors
// were a dropped `--run`, and on 2026-08-05 a seat typed `special circumstances` where the
// path has a hyphen, was told its own gap did not exist, filed a false bug report and
// abandoned five manifest receipts.
//
// setup knows the run and runs BEFORE the workflow, so it writes a wrapper here and prints its
// directory as the `binDir` to hand the workflow. The prompt already interpolates
// "${binDir}/feov-record", so the engine is unchanged and no seat learns a new word.
//
// A MISTYPED PATH DOES NOT EXIST. That is the whole trade: a wrong `--run` is well-formed and
// silently files a seat's work against nothing, while a wrong wrapper path fails loudly at the
// shell before the tool is reached.
//
// It carries the run in the ENVIRONMENT rather than as `--run`, because a wrapper passing a
// flag is overridden by a seat's own `--run` (last one wins), which reinstates the typo in
// exactly the runs the hook is not reaching — the ones this exists for. seatenv already treats
// the environment as outranking the flag and refuses a disagreement, so the channel is the one
// that already has a gate on it.
const (
	// WrapperDir is the run-relative directory the wrapper is written into. It is dotted so it
	// sorts out of the way of the run's actual contents, and it holds no records: capture takes
	// records and proofs, and a regenerable shim is neither.
	WrapperDir = ".bin"
	// WrapperName must match what the prompt appends to binDir, or the wrapper is never run.
	WrapperName = "feov-record"
)

// WrapperResult reports what was written, for the summary and for tests.
type WrapperResult struct {
	// BinDir is the value to hand the workflow as `binDir`. Empty when no wrapper was written.
	BinDir string
	// Target is the real binary the wrapper execs.
	Target string
	// Skipped, when non-empty, says why no wrapper exists — so the summary can say "not
	// measured" rather than print a path that would not run.
	Skipped string
}

// WriteRunWrapper writes <runDir>/.bin/feov-record (and .cmd) execing recordBin with the run
// directory in the environment. runDir should already be absolute.
func WriteRunWrapper(run record.Run, recordBin string) WrapperResult {
	runDir := run.Dir()
	target, err := resolveTarget(recordBin)
	if err != nil {
		return WrapperResult{Skipped: err.Error()}
	}
	dir := filepath.Join(runDir, WrapperDir)
	// REFUSING TO WRAP A WRAPPER. Pointing --bin-dir at a previous run's .bin would produce a
	// shim that execs a shim carrying a DIFFERENT run's directory — and the inner one wins,
	// because it sets the variable last. That is the cross-run misfiling this whole mechanism
	// exists to prevent, arrived at through the mechanism itself.
	if sameFile(filepath.Dir(target), dir) || filepath.Base(filepath.Dir(target)) == WrapperDir {
		return WrapperResult{Skipped: fmt.Sprintf(
			"the record binary at %s is itself a per-run wrapper; point --bin-dir at the real binary", target)}
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return WrapperResult{Skipped: err.Error()}
	}

	sh := "#!/bin/sh\n" +
		"# Generated by `feov-record setup`. Regenerable; not a record.\n" +
		"# Binds this run to every seat call so no seat has to type --run. See internal/setup/wrapper.go.\n" +
		shExport(seatenv.VarWrapper, runDir) +
		"exec " + shQuote(target) + " \"$@\"\n"
	if err := os.WriteFile(filepath.Join(dir, WrapperName), []byte(sh), 0o755); err != nil {
		return WrapperResult{Skipped: err.Error()}
	}

	// The CI matrix runs windows-latest and an operator may launch there. A .cmd costs two
	// lines and its absence would be a platform where the run silently falls back to the seat
	// typing --run — the case this removes.
	cmd := "@echo off\r\n" +
		"rem Generated by `feov-record setup`. Regenerable; not a record.\r\n" +
		"set \"" + seatenv.VarWrapper + "=" + runDir + "\"\r\n" +
		"\"" + target + "\" %*\r\n"
	if err := os.WriteFile(filepath.Join(dir, WrapperName+".cmd"), []byte(cmd), 0o755); err != nil {
		return WrapperResult{Skipped: err.Error()}
	}
	return WrapperResult{BinDir: dir, Target: target}
}

// resolveTarget turns whatever --bin-dir produced into an absolute path to a real file. A bare
// name is looked up on PATH; anything else is made absolute, because the wrapper runs from the
// seat's cwd and a relative target would resolve against the wrong directory.
func resolveTarget(recordBin string) (string, error) {
	if recordBin == "" {
		return "", fmt.Errorf("no record binary was resolved")
	}
	if !strings.ContainsRune(recordBin, filepath.Separator) && !strings.ContainsRune(recordBin, '/') {
		p, err := exec.LookPath(recordBin)
		if err != nil {
			return "", fmt.Errorf("%s is not on PATH: %v", recordBin, err)
		}
		recordBin = p
	}
	abs, err := filepath.Abs(recordBin)
	if err != nil {
		return "", err
	}
	if st, err := os.Stat(abs); err != nil || st.IsDir() {
		return "", fmt.Errorf("%s is not a file", abs)
	}
	return abs, nil
}

// shExport writes a POSIX assignment+export with the value single-quoted, so a path containing
// a space or a shell metacharacter cannot become two words or a command.
func shExport(name, value string) string {
	return name + "=" + shQuote(value) + "\nexport " + name + "\n"
}

// shQuote single-quotes s for /bin/sh, closing and reopening around any embedded quote.
func shQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }

func sameFile(a, b string) bool {
	ai, err := os.Stat(a)
	if err != nil {
		return false
	}
	bi, err := os.Stat(b)
	if err != nil {
		return false
	}
	return os.SameFile(ai, bi)
}
