// Command schemagen derives the event-schema epoch the record binary compiles in, from the
// manifest that declares it.
//
// Dev tooling for this repository only. Nothing here ships to an installing project.
//
// # What the epoch is
//
// One integer answering one question: does this binary write the event shape the plugin's
// prompts read. It moves only when that shape changes incompatibly. Equal runs, unequal
// refuses — there is no compatibility window, because none is promised.
//
// It replaced a semver string compared with `!=`, and the difference is not cosmetic. A
// release number moves for reasons the schema does not care about, so the check tracked
// SHIPPING rather than compatibility, and every release had to remember to bump a second
// number to keep it honest. An epoch has nothing to keep in step with.
//
// # Why generated
//
// requirements.json is the authority — it ships beside the prompts the run will drive — and
// the binary has to carry the same number to be checkable at all. Two hand-written copies of
// one fact is the shape this repository generates its way out of everywhere else, so this
// generates too: `-check` fails when the compiled-in constant and the manifest disagree.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/ctoforaday/special-circumstances/scripts/internal/gitx"
)

const (
	manifestPath = "plugins/frank-exchange-of-views/requirements.json"
	outPath      = "plugins/frank-exchange-of-views/tools/internal/record/schema_gen.go"
)

func main() {
	check := flag.Bool("check", false, "verify the compiled-in epoch matches the manifest instead of writing it")
	flag.Parse()

	root, err := gitx.Root()
	if err != nil {
		fmt.Fprintln(os.Stderr, "schemagen:", err)
		os.Exit(1)
	}
	want, epoch, err := generate(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "schemagen:", err)
		os.Exit(1)
	}
	target := filepath.Join(root, outPath)

	if !*check {
		if err := os.WriteFile(target, want, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "schemagen:", err)
			os.Exit(1)
		}
		fmt.Printf("schemagen: wrote %s (epoch %d)\n", outPath, epoch)
		return
	}
	got, err := os.ReadFile(target)
	if err != nil {
		fmt.Fprintf(os.Stderr, "schemagen: %s is missing (%v) — run `(cd scripts && go run ./schemagen)`\n", outPath, err)
		os.Exit(1)
	}
	if !bytes.Equal(got, want) {
		fmt.Fprintf(os.Stderr, "schemagen: the compiled-in epoch disagrees with %s.\n"+
			"setup compares the binary's epoch against that manifest, so a disagreement here means\n"+
			"either every binary is refused or — if the manifest is the one that moved — none is.\n"+
			"Regenerate: (cd scripts && go run ./schemagen)\n", manifestPath)
		os.Exit(1)
	}
	fmt.Printf("schemagen: the compiled-in epoch matches %s (epoch %d)\n", manifestPath, epoch)
}

func generate(root string) ([]byte, int, error) {
	raw, err := os.ReadFile(filepath.Join(root, manifestPath))
	if err != nil {
		return nil, 0, err
	}
	var m struct {
		EventSchema *int `json:"eventSchema"`
	}
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, 0, fmt.Errorf("parsing %s: %w", manifestPath, err)
	}
	// A POINTER, so "absent" and "zero" are different answers. Absent means the manifest has
	// stopped declaring the epoch, which would make every comparison compare nothing; zero is
	// a value somebody chose. Neither is acceptable, and they must not be confused.
	if m.EventSchema == nil {
		return nil, 0, fmt.Errorf("%s declares no eventSchema — setup would then compare the binary against nothing", manifestPath)
	}
	if *m.EventSchema < 1 {
		return nil, 0, fmt.Errorf("%s declares eventSchema %d; the epoch starts at 1 so that an unset field cannot pass for a real one", manifestPath, *m.EventSchema)
	}
	epoch := *m.EventSchema

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by scripts/schemagen from %s. DO NOT EDIT.

package record

// EventSchema is the event-shape epoch this binary writes.
//
// setup refuses to start a run when the binary's epoch differs from the one in the plugin's
// requirements.json. It answers one question — does this binary write the shape these prompts
// read — and it moves only when that shape changes incompatibly.
//
// It is not a version. Nothing here promises backwards compatibility, so there is no window
// to describe and no delta list to maintain: equal runs, unequal refuses.
const EventSchema = %d
`, manifestPath, epoch)
	src, err := format.Source(b.Bytes())
	return src, epoch, err
}
