// Command buildidgen propagates the one authored buildid package into every plugin module.
//
// Dev tooling for this repository only. Nothing here ships to an installing project.
//
// # Why copies at all
//
// Each plugin's tools/ has to build on its own: `sc-doctor --fix` runs
// `go build -C <installedPluginRoot>/tools ./cmd/<name>`, and a consumer with one plugin
// installed has only that plugin's tree on disk. A shared module they all import would make
// that build fail, so the modules stay separate and the code is copied.
//
// # Why generated copies
//
// Because hand-written ones drift, and had. The two existing copies were identical in
// substance and different in comments, and only one of them carried ExeName — so the module
// without it hand-rolled the same `.exe` conditional inside a test, which is how a rule about
// executable naming ends up stated twice and enforced once.
//
// One authored package under scripts/internal/buildid, compiled and tested there; a copy
// written into each module; `-check` fails when a copy has drifted. The copies carry a
// DO NOT EDIT header so the next person edits the source instead of a leaf.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ctoforaday/special-circumstances/scripts/internal/gitx"
)

// srcDir is the authored package. targets are the modules that need a copy of it.
const srcDir = "scripts/internal/buildid"

var targets = []string{
	"plugins/prosthetic-conscience/tools/internal/buildid",
	"plugins/gray-area/tools/internal/buildid",
	"plugins/frank-exchange-of-views/tools/internal/buildid",
}

func main() {
	check := flag.Bool("check", false, "verify every copy matches the authored source instead of writing them")
	flag.Parse()

	root, err := gitx.Root()
	if err != nil {
		fmt.Fprintln(os.Stderr, "buildidgen:", err)
		os.Exit(1)
	}
	want, err := render(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "buildidgen:", err)
		os.Exit(1)
	}

	var stale []string
	for _, t := range targets {
		for name, body := range want {
			path := filepath.Join(root, t, name)
			if !*check {
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					fmt.Fprintln(os.Stderr, "buildidgen:", err)
					os.Exit(1)
				}
				if err := os.WriteFile(path, body, 0o644); err != nil {
					fmt.Fprintln(os.Stderr, "buildidgen:", err)
					os.Exit(1)
				}
				continue
			}
			got, err := os.ReadFile(path)
			if err != nil {
				stale = append(stale, fmt.Sprintf("%s/%s is missing (%v)", t, name, err))
				continue
			}
			if !bytes.Equal(got, body) {
				stale = append(stale, fmt.Sprintf("%s/%s has drifted from %s/%s", t, name, srcDir, name))
			}
		}
	}

	if !*check {
		fmt.Printf("buildidgen: wrote %d file(s) into %d module(s)\n", len(want), len(targets))
		return
	}
	if len(stale) > 0 {
		for _, s := range stale {
			fmt.Fprintln(os.Stderr, "buildidgen:", s)
		}
		fmt.Fprintf(os.Stderr, "buildidgen: edit %s and run `(cd scripts && go run ./buildidgen)` — "+
			"the copies are generated so the rule they carry is stated once.\n", srcDir)
		os.Exit(1)
	}
	fmt.Printf("buildidgen: %d module(s) match %s\n", len(targets), srcDir)
}

// render reads the authored package and returns each file's generated form.
func render(root string) (map[string][]byte, error) {
	entries, err := os.ReadDir(filepath.Join(root, srcDir))
	if err != nil {
		return nil, err
	}
	out := map[string][]byte{}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		body, err := os.ReadFile(filepath.Join(root, srcDir, name))
		if err != nil {
			return nil, err
		}
		var b bytes.Buffer
		fmt.Fprintf(&b, "// Code generated by scripts/buildidgen from %s/%s. DO NOT EDIT.\n\n", srcDir, name)
		b.Write(body)
		out[name] = b.Bytes()
	}
	// An authored package that reads as EMPTY would generate nothing and report success,
	// leaving whatever is already in the modules untouched and unchecked.
	if len(out) == 0 {
		return nil, fmt.Errorf("%s holds no non-test .go files — refusing to generate nothing", srcDir)
	}
	return out, nil
}
