// Command vocabdoc generates the frank-exchange-of-views plugin's docs/vocabulary.md from its terms
// registry; with -check it fails when the committed page is stale.
//
// Dev tooling for this repository only. Nothing here ships to an installing project.
//
// # Why generated
//
// The registry (tools/internal/terms/terms.json) is the single source of the protocol's concept
// nouns: `manual` prints each seat the definitions its surface uses, and the vocabulary gate holds
// every seat-facing surface to its bans. A page a human reads beside it would be a second
// hand-written copy of the same facts, so it is generated, and CI refuses a stale one.
//
// # Why it reads the file by path
//
// The scripts module cannot import the plugin's internal packages, so the registry's shape is
// restated here. It is decoded with unknown fields refused: a field the registry gains and this
// does not know is an error, not a column silently missing from the page.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/ctoforaday/special-circumstances/scripts/internal/gitx"
)

const (
	registryPath = "plugins/frank-exchange-of-views/tools/internal/terms/terms.json"
	outPath      = "plugins/frank-exchange-of-views/docs/vocabulary.md"
)

type registry struct {
	Entries []entry `json:"entries"`
}

type entry struct {
	Term       string      `json:"term"`
	Definition string      `json:"definition"`
	Seats      []string    `json:"seats"`
	Bans       []ban       `json:"bans"`
	Collisions []collision `json:"collisions"`
}

type ban struct {
	Variant string  `json:"variant"`
	Kind    string  `json:"kind"`
	Pattern string  `json:"pattern"`
	Masks   []mask  `json:"masks"`
	Allow   []allow `json:"allow"`
}

type mask struct {
	Phrase string `json:"phrase"`
	Reason string `json:"reason"`
}

type allow struct {
	Path   string `json:"path"`
	Reason string `json:"reason"`
}

type collision struct {
	Word       string `json:"word"`
	Resolution string `json:"resolution"`
}

func main() {
	check := flag.Bool("check", false, "verify the committed page matches the registry instead of writing it")
	flag.Parse()

	root, err := gitx.Root()
	if err != nil {
		fail(err)
	}
	want, err := generate(root)
	if err != nil {
		fail(err)
	}
	target := filepath.Join(root, outPath)
	if !*check {
		if err := os.WriteFile(target, want, 0o644); err != nil {
			fail(err)
		}
		fmt.Printf("vocabdoc: wrote %s\n", outPath)
		return
	}
	got, err := os.ReadFile(target)
	if err != nil {
		fmt.Fprintf(os.Stderr, "vocabdoc: %s is missing (%v) — run `(cd scripts && go run ./vocabdoc)`\n", outPath, err)
		os.Exit(1)
	}
	if !bytes.Equal(got, want) {
		fmt.Fprintf(os.Stderr, "vocabdoc: %s is stale against %s.\n"+
			"The page is generated; edit the registry, never the page.\n"+
			"Regenerate: (cd scripts && go run ./vocabdoc)\n", outPath, registryPath)
		os.Exit(1)
	}
	fmt.Printf("vocabdoc: %s matches %s\n", outPath, registryPath)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "vocabdoc:", err)
	os.Exit(1)
}

func generate(root string) ([]byte, error) {
	raw, err := os.ReadFile(filepath.Join(root, registryPath))
	if err != nil {
		return nil, err
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	var r registry
	if err := dec.Decode(&r); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", registryPath, err)
	}
	if len(r.Entries) == 0 {
		return nil, fmt.Errorf("%s holds no entries — the page would say the protocol has no vocabulary", registryPath)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "<!-- Code generated by scripts/vocabdoc from %s. DO NOT EDIT. -->\n\n", registryPath)
	b.WriteString("# The protocol's vocabulary\n\n")
	b.WriteString("One word for each concept the protocol's prose names. This page is generated from the terms " +
		"registry, `tools/internal/terms/terms.json`. The same registry is what `manual` prints to each seat as " +
		"WORDS THIS SURFACE USES, and what the vocabulary gate (`TestVocabularyProse`, in " +
		"`tools/integration/surface`) holds every seat-facing surface to. Change the registry, then regenerate: " +
		"`(cd scripts && go run ./vocabdoc)`.\n\n")
	b.WriteString("A **GATED** variant fails the gate wherever it appears, unless a mask blanks it or an allow exempts " +
		"its file. A **REGISTRY-ONLY** variant is defined here and not gated, because the word has a legitimate " +
		"neighbour sense no exact phrase can tell apart. A **mask** is a legitimate phrase blanked before the " +
		"pattern runs; an **allow** exempts a file, and says why.\n\n")

	b.WriteString("| term | delivered to |\n|---|---|\n")
	for _, e := range r.Entries {
		fmt.Fprintf(&b, "| [%s](#%s) | %s |\n", cell(e.Term), slug(e.Term), cell(strings.Join(e.Seats, ", ")))
	}
	b.WriteString("\n")

	for _, e := range r.Entries {
		fmt.Fprintf(&b, "## %s\n\n%s\n\n**Delivered to:** %s\n\n", e.Term, e.Definition, strings.Join(e.Seats, ", "))
		if len(e.Bans) > 0 {
			b.WriteString("**Not:**\n\n| variant | kind | pattern | masks | allowed in |\n|---|---|---|---|---|\n")
			for _, x := range e.Bans {
				var masks, allows []string
				for _, m := range x.Masks {
					masks = append(masks, code(m.Phrase)+" — "+m.Reason)
				}
				for _, a := range x.Allow {
					allows = append(allows, code(a.Path)+" — "+a.Reason)
				}
				fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", cell(x.Variant), x.Kind, cell(code(x.Pattern)),
					cell(strings.Join(masks, "<br>")), cell(strings.Join(allows, "<br>")))
			}
			b.WriteString("\n")
		}
		if len(e.Collisions) > 0 {
			b.WriteString("**Collisions:**\n\n")
			for _, c := range e.Collisions {
				fmt.Fprintf(&b, "- **%s** — %s\n", c.Word, c.Resolution)
			}
			b.WriteString("\n")
		}
	}
	return append(bytes.TrimRight(b.Bytes(), "\n"), '\n'), nil
}

// code wraps s in a code span, or returns "" for an empty s.
func code(s string) string {
	if s == "" {
		return ""
	}
	return "`" + s + "`"
}

// cell makes s safe inside a table cell: a pipe would end the cell, code span or not.
func cell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

var nonSlug = regexp.MustCompile(`[^a-z0-9 -]`)

// slug is the anchor GitHub gives a heading: lowercase, punctuation dropped, spaces as hyphens.
func slug(s string) string {
	return strings.ReplaceAll(nonSlug.ReplaceAllString(strings.ToLower(s), ""), " ", "-")
}
