package fetchcache

import (
	"encoding/json"
	"net/url"
	"regexp"
	"strings"
)

// THE SOURCES THAT CONTRIBUTE LOCATIONS, AND WHY EACH IS A DIFFERENT OPINION.
//
// One index's list is not the world: eight works whose publisher pdf_url answered 403 were
// re-checked by hand and four carried a PubMed Central copy the first index never surfaced. The
// lesson generalises past that one case — what matters is not which index is best but that each
// is a DIFFERENT ORGANISATION with its own crawl. Unpaywall was dropped for failing exactly that
// test: it is a wrapper over OpenAlex and contributed 0 unique urls across 30 works.
//
// Each source here answers (locations, answered). `answered` false means the service did not
// speak — a timeout, a 5xx, a body that is not what it should be — and it is never the same as
// "this service knows of no copy". The distinction is load-bearing: the caller assembles a
// determinate "no open copy exists anywhere" only when EVERY source answered, because that claim
// cannot be built out of a timeout.

// semanticScholarCandidates asks Semantic Scholar, which runs its own crawl and its own PDF
// discovery rather than deriving from Crossref.
//
// MEASURED VALUE: MODEST, AND WORTH SAYING SO. On the eight works that had defeated the other
// route it mostly echoed the same publisher urls that had already refused us. It is included
// because it is genuinely independent and free, not because it carried that test.
func semanticScholarCandidates(f Fetcher, doi string) (locs []string, answered bool) {
	if doi == "" {
		return nil, true
	}
	resp, err := f.Fetch("https://api.semanticscholar.org/graph/v1/paper/DOI:" +
		url.PathEscape(doi) + "?fields=openAccessPdf,externalIds")
	if err != nil {
		return nil, false
	}
	var r struct {
		PaperID       string `json:"paperId"` // the discriminator: an error body decodes without it
		OpenAccessPDF *struct {
			URL string `json:"url"`
		} `json:"openAccessPdf"`
		ExternalIDs map[string]any `json:"externalIds"`
	}
	if json.Unmarshal(resp.Body, &r) != nil {
		return nil, false
	}
	// A 404 for a doi it does not hold is an ANSWER — it knows of no copy — and arrives as a
	// refusal above, so reaching here with no paperId means the shape moved.
	if r.PaperID == "" {
		return nil, false
	}
	if r.OpenAccessPDF != nil && r.OpenAccessPDF.URL != "" {
		locs = append(locs, r.OpenAccessPDF.URL)
	}
	return locs, true
}

// doajCandidates asks the Directory of Open Access Journals, which indexes peer-reviewed open
// journals NATIVELY — a publisher applies and is assessed — rather than inferring openness from
// a crawl. That makes it a different KIND of evidence from the others, not merely another crawl:
// where DOAJ lists a full-text url, a human has checked that the journal is open.
func doajCandidates(f Fetcher, doi string) (locs []string, answered bool) {
	if doi == "" {
		return nil, true
	}
	resp, err := f.Fetch("https://doaj.org/api/search/articles/doi:" + url.PathEscape(doi))
	if err != nil {
		return nil, false
	}
	var r struct {
		Total   *int `json:"total"` // present even on a zero-result answer; absent on an error body
		Results []struct {
			Bibjson struct {
				Link []struct {
					Type        string `json:"type"`
					URL         string `json:"url"`
					ContentType string `json:"content_type"`
				} `json:"link"`
			} `json:"bibjson"`
		} `json:"results"`
	}
	if json.Unmarshal(resp.Body, &r) != nil || r.Total == nil {
		return nil, false
	}
	for _, res := range r.Results {
		for _, l := range res.Bibjson.Link {
			if l.Type == "fulltext" && l.URL != "" {
				locs = append(locs, l.URL)
			}
		}
	}
	return locs, true
}

// citationPDFRe reads the `citation_pdf_url` meta tag, in either attribute order.
var citationPDFRe = regexp.MustCompile(`(?is)<meta[^>]+(?:name\s*=\s*["']?citation_pdf_url["']?[^>]*content\s*=\s*["']([^"']+)["']|content\s*=\s*["']([^"']+)["'][^>]*name\s*=\s*["']?citation_pdf_url["']?)`)

// LandingPagePDF reads a landing page's own statement of where its PDF is.
//
// THE PAGE IN FRONT OF US IS A SOURCE OF LOCATIONS TOO, and the cheapest one: it costs no request
// at all, because the bytes are already in hand. Google Scholar's inclusion guidelines are why
// the tag is so widely present — publishers emit `citation_pdf_url` to be indexed, and it points
// at the file rather than the viewer.
//
// It is also the one signal a publisher cannot be wrong about. An index may hold a stale url; the
// page saying "my pdf is here" was generated by the system serving it.
//
// Signposting (`Link: rel="item"`) is the standards-track version of the same idea and is read
// from the header where a host sends one — repository platforms do, commercial publishers do not.
func LandingPagePDF(contentType string, body []byte, linkHeader string, base *url.URL) string {
	if base == nil {
		return ""
	}
	if rel := signpostItem(linkHeader); rel != "" {
		if u := resolveWeb(base, rel); u != "" {
			return u
		}
	}
	if !strings.Contains(strings.ToLower(contentType), "html") {
		return ""
	}
	m := citationPDFRe.FindSubmatch(body)
	if m == nil {
		return ""
	}
	raw := string(m[1])
	if raw == "" {
		raw = string(m[2])
	}
	return resolveWeb(base, strings.TrimSpace(raw))
}

// signpostItem pulls the FAIR Signposting `rel="item"` target out of a Link header, preferring a
// pdf where the header types its links.
func signpostItem(header string) string {
	if header == "" {
		return ""
	}
	for _, part := range strings.Split(header, ",") {
		if !strings.Contains(strings.ToLower(part), `rel="item"`) && !strings.Contains(strings.ToLower(part), "rel=item") {
			continue
		}
		open, close := strings.Index(part, "<"), strings.Index(part, ">")
		if open < 0 || close <= open {
			continue
		}
		return strings.TrimSpace(part[open+1 : close])
	}
	return ""
}

func resolveWeb(base *url.URL, ref string) string {
	if ref == "" {
		return ""
	}
	r, err := url.Parse(ref)
	if err != nil {
		return ""
	}
	abs := base.ResolveReference(r)
	if abs.Scheme != "http" && abs.Scheme != "https" {
		return ""
	}
	return abs.String()
}
