package cli

import (
	"strings"
	"testing"

	"github.com/ctoforaday/special-circumstances/plugins/frank-exchange-of-views/tools/internal/cli/seat"
	"github.com/ctoforaday/special-circumstances/plugins/frank-exchange-of-views/tools/internal/flags"
	"github.com/ctoforaday/special-circumstances/plugins/frank-exchange-of-views/tools/internal/record/recordpb"
)

func eventTypeWord(word string) (recordpb.EventType, bool) {
	vs := recordpb.EventType(0).Descriptor().Values()
	for i := 0; i < vs.Len(); i++ {
		if t := recordpb.EventType(vs.Get(i).Number()); word != "" && recordpb.Word(t) == word {
			return t, true
		}
	}
	return 0, false
}

// EVERY CORRECTABLE VERB TEACHES THE CORRECTION ON ITS OWN PAGE, AND NO OTHER VERB DOES.
//
// The paragraph is generated by seat.Correctable, so this checks the attachment survives every
// verb's construction and that no verb offers the flags without the page saying how they work.
func TestEveryCorrectableVerbTeachesTheCorrection(t *testing.T) {
	const first = "CORRECTING WHAT YOU RECORDED."
	n := 0
	for path, c := range commandsByPath() {
		has := strings.Contains(seat.HelpText(c), first)
		flagged := c.Flags().Lookup(flags.Corrects) != nil || c.Flags().Lookup(flags.CorrectionWhy) != nil
		switch {
		case seat.IsCorrectable(c):
			n++
			if !has {
				t.Errorf("%s takes a correction and its help does not say how", path)
			}
			if c.Flags().Lookup(flags.Corrects) == nil || c.Flags().Lookup(flags.CorrectionWhy) == nil {
				t.Errorf("%s is correctable and lacks --corrects or --correction-why", path)
			}
		case has:
			t.Errorf("%s teaches a correction it does not take", path)
		case flagged:
			t.Errorf("%s carries a correction flag without being correctable", path)
		}
	}
	if n < 28 {
		t.Fatalf("only %d correctable verbs — the walk is not seeing the surface", n)
	}
}

// A COMMAND IS CORRECTABLE EXACTLY WHEN IT RECORDS A CORRECTABLE TYPE.
//
// The record type is what the correction's tier is read from and what the success line's key is
// matched on. A verb whose RecordType is its NAME rather than its event's word (`manifest-row`,
// `spot-check`, `inquiry-support`) resolves to no type: Correctable would refuse it, and the key
// suffix would never match. The reverse is the omission: a verb writing a FULL or PROSE act with no
// way to correct it.
func TestACommandIsCorrectableExactlyWhenItRecordsACorrectableType(t *testing.T) {
	byPath := commandsByPath()
	for path, word := range CommandRecords() {
		c := byPath[path]
		typ, known := eventTypeWord(word)
		correctableType := known && recordpb.Tier(typ) != recordpb.CorrectionTier_CORRECTION_TIER_NONE
		switch {
		case seat.IsCorrectable(c) && !known:
			t.Errorf("%s is correctable and records %q, which is no event type — declare the event with seat.Records", path, word)
		case seat.IsCorrectable(c) && !correctableType:
			t.Errorf("%s is correctable and records a %s, which the record refuses to correct", path, word)
		case !seat.IsCorrectable(c) && correctableType:
			t.Errorf("%s records a %s, which is correctable, and offers no correction", path, word)
		}
	}
}
