// Package hookfailures keeps the failures a hook swallows, and says them where a human looks.
//
// GENERATED by scripts/hookfailgen from one authored file — edit that, never this copy, and run
// `go -C scripts run ./hookfailgen`. The three plugins are separate Go modules by design, so this
// cannot be imported; `scripts/check` fails on drift between the copies.
//
// # The defect this closes
//
// A hook's stdout and stderr at exit 0 reach the client's debug log and nowhere else — measured:
// a token written to stderr appears in the transcript only inside a `hook_success` record whose
// `content` is empty, in no tool result, and a live session asked straight afterwards reported it
// had received no such text. Every hook in this suite exits 0 by contract, so every failure
// reported that way was reported to nobody, for as long as it lasted.
//
// # The shape
//
// Each failure is a FIELD on a record, keyed by the STAGE that failed and the SCOPE it failed in
// (a project, or empty for the machine), and cleared by that stage's own next success — so "no
// entry" means the stage last WORKED, never "nothing looked". A failure on an event the client
// displays nothing for is KEPT until one that does: that is what the record buys over speaking at
// the moment of failure, and five of the events in this suite display nothing.
//
// The events that display a top-level systemMessage are SessionStart, PreToolUse, PostToolUse,
// PostToolUseFailure and Stop. Settle returns the message rather than printing it, because most
// hooks here already emit a JSON document of their own and a second top-level object would corrupt
// it: each binary merges the text into its own response, and one with nothing to emit calls Emit.
//
// SubagentStart and SubagentStop CARRY NO MESSAGE TO A HUMAN, whatever happens: neither is a
// displaying event, so nothing special is needed beyond never calling Emit on them. A failure at
// either waits for the next event that displays.
//
// THAT IS NOT THE SAME AS SILENCE. SubagentStop must emit nothing at all — an emission there
// re-invokes the seat, nine firings measured — while SubagentStart's document is a per-seat
// injection channel that a plugin may legitimately use. What this package governs is the FAULT
// channel, and a fault is never said on either.
//
// # What is deliberately accepted
//
// Concurrent hooks race: each writer loads, merges and renames over the file, so the last writer
// wins. A hook must never wait, and the cost is bounded — a lost failure is recorded again the next
// time the stage fails, and a lost clear shows one stale entry until that stage next works.
package hookfailures

import (
	"cmp"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync"
	"time"
)

// Stage names what failed. Each stage is declared by the package that can fail it, so a new failure
// path cannot be added without naming what it is. The set is the record's key space: a reader asks
// "is the catalogue opening", never parses a message for it.
type Stage string

// NotifyEvery is how long a stage that is still failing stays unannounced after being shown. Stop
// and PreToolUse fire constantly; without it a broken machine would speak on every turn.
const NotifyEvery = 10 * time.Minute

// Schema versions failures.json.
const Schema = 1

// Failure is one entry.
type Failure struct {
	Stage Stage `json:"stage"`
	// Scope is the project a project-scoped failure happened in, and empty for a machine-scoped
	// one. It is part of the identity: a manifest that works in one project must not clear the
	// entry of another whose manifest does not.
	Scope    string    `json:"scope,omitempty"`
	Error    string    `json:"error"`
	Event    string    `json:"event"` // the hook event that last hit it
	Since    time.Time `json:"since"` // first failure since the stage last worked
	Last     time.Time `json:"last"`
	Notified time.Time `json:"notified,omitzero"` // last time a displaying event showed it
}

// Record is the file's shape.
type Record struct {
	Schema   int       `json:"schema"`
	Failures []Failure `json:"failures"`
}

type key struct {
	stage Stage
	scope string
}

func (f Failure) key() key { return key{f.Stage, f.Scope} }

// Recorder collects one invocation's outcomes and settles them into the record at the end.
//
// IT IS SHARED BY CONCURRENT UNITS, so its maps are guarded: prosthetic-conscience's hookunit fans
// an event's units out over goroutines, and every one of them records — which crashed the process
// with "concurrent map writes" the first time a second unit was wired in. A hook that PANICS is
// worse than the silence this package exists to end, so the lock is not optional and the race
// detector runs over this in CI.
type Recorder struct {
	mu      sync.Mutex
	plugin  string
	speaker string
	event   string
	now     time.Time
	stderr  io.Writer
	failed  map[key]string
	worked  map[key]bool
}

// New starts a recorder for one hook invocation.
//
// plugin names the record's DIRECTORY, and is the plugin because a plugin's binaries share one
// record: a session wants one message listing what is broken, not one per binary. speaker names the
// BINARY, and is what every line and message it writes is prefixed with, because the debug log and
// the human both need to know which of a plugin's hooks is talking. event decides whether anything
// can be said at all.
func New(plugin, speaker, event string, now time.Time, stderr io.Writer) *Recorder {
	return &Recorder{plugin: plugin, speaker: speaker, event: event, now: now, stderr: stderr,
		failed: map[key]string{}, worked: map[key]bool{}}
}

// Fail says the failure on stderr, for the debug log, and records it.
func (r *Recorder) Fail(s Stage, detail string) { r.FailIn(s, "", detail) }

// OK records that a stage worked, which clears its entry.
func (r *Recorder) OK(s Stage) { r.OKIn(s, "") }

// FailIn and OKIn are Fail and OK for a stage whose entries are per scope.
func (r *Recorder) FailIn(s Stage, scope, detail string) {
	r.mu.Lock()
	defer r.mu.Unlock()
	fmt.Fprintln(r.stderr, r.speaker+": "+detail)
	r.failed[key{s, scope}] = detail
}

func (r *Recorder) OKIn(s Stage, scope string) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.worked[key{s, scope}] = true
}

// Failed reports whether anything failed in this invocation, for a caller that must know before it
// composes its response.
func (r *Recorder) Failed() bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	return len(r.failed) > 0
}

// Displays reports whether the client shows a top-level systemMessage from this hook event.
func Displays(event string) bool {
	switch event {
	case "SessionStart", "PreToolUse", "PostToolUse", "PostToolUseFailure", "Stop":
		return true
	}
	return false
}

// Path is the record's location: beside the plugin's state, never inside a directory a failure may
// be about — a catalogue directory that cannot be created must not take its own failure record down
// with it.
func Path(plugin string) (string, error) {
	if x := os.Getenv("XDG_STATE_HOME"); x != "" {
		return filepath.Join(x, "special-circumstances", plugin, "failures.json"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("no home directory: %w", err)
	}
	return filepath.Join(home, ".local", "state", "special-circumstances", plugin, "failures.json"), nil
}

// Settle merges this invocation into the record and returns the message the caller should show, or
// "" when there is nothing due or the event displays nothing.
//
// It RETURNS the text rather than printing it: a hook that already emits a JSON document must merge
// this into that document's systemMessage field, because two top-level objects on stdout are not a
// response. Emit is for a hook with nothing else to say.
func (r *Recorder) Settle() string {
	r.mu.Lock()
	defer r.mu.Unlock()
	path, pathErr := Path(r.plugin)
	rec, persistErr := r.merge(path, pathErr)
	if persistErr != nil {
		// NO RECORD, SO NO THROTTLE: say what this invocation saw, and why it could not be kept.
		fmt.Fprintf(r.stderr, "%s: failure record not kept: %v\n", r.speaker, persistErr)
		if !Displays(r.event) || len(r.failed) == 0 {
			return ""
		}
		var due []Failure
		for k, d := range r.failed {
			due = append(due, Failure{Stage: k.stage, Scope: k.scope, Error: d, Event: r.event, Since: r.now, Last: r.now})
		}
		sortFailures(due)
		return render(r.speaker, due, "", persistErr)
	}
	if !Displays(r.event) {
		return ""
	}
	var due []Failure
	for i, f := range rec.Failures {
		if f.Notified.IsZero() || r.now.Sub(f.Notified) >= NotifyEvery {
			rec.Failures[i].Notified = r.now
			due = append(due, rec.Failures[i])
		}
	}
	if len(due) == 0 {
		return ""
	}
	if err := save(path, rec); err != nil {
		fmt.Fprintf(r.stderr, "%s: failure record not kept: %v\n", r.speaker, err)
	}
	return render(r.speaker, due, path, nil)
}

// Persist merges this invocation into the record and says NOTHING — and, unlike a Settle whose
// message is thrown away, marks nothing as said.
//
// That difference is the whole method. A caller that cannot speak on this call — no project root,
// so no stdout at all; or a response that just failed to write — used to call Settle and discard the
// result. On a displaying event Settle stamps every due entry as NOTIFIED, so the discarded message
// counted as shown: the human was never told, and the entry then sat out the full quiet period
// before anything would try again. Persist keeps the record and leaves the telling to the next call
// that can.
func (r *Recorder) Persist() {
	r.mu.Lock()
	defer r.mu.Unlock()
	path, pathErr := Path(r.plugin)
	if _, err := r.merge(path, pathErr); err != nil {
		fmt.Fprintf(r.stderr, "%s: failure record not kept: %v\n", r.speaker, err)
	}
}

// Emit writes the one top-level object a hook with no document of its own uses to speak. It writes
// nothing for an empty message, because silence is a valid response and an empty object is not.
func Emit(stdout io.Writer, msg string) {
	if msg == "" {
		return
	}
	b, err := json.Marshal(struct {
		SystemMessage string `json:"systemMessage"`
	}{msg})
	if err != nil {
		return
	}
	fmt.Fprintln(stdout, string(b))
}

// merge loads the record, applies this invocation and saves it when anything changed. A healthy
// invocation with no record on disk writes nothing.
func (r *Recorder) merge(path string, pathErr error) (Record, error) {
	if pathErr != nil {
		return Record{}, pathErr
	}
	rec, err := load(path)
	changed := false
	var unreadable errUnreadable
	switch {
	case errors.As(err, &unreadable):
		// Replaced, not kept broken: an unreadable record would otherwise disable the throttle for
		// good. What it held is lost; any stage still failing is recorded again as it fails.
		fmt.Fprintf(r.stderr, "%s: replacing the failure record: %v\n", r.speaker, err)
		changed = true
	case err != nil:
		return Record{}, err
	}
	kept := rec.Failures[:0]
	for _, f := range rec.Failures {
		_, failedNow := r.failed[f.key()]
		if r.worked[f.key()] && !failedNow {
			changed = true
			continue
		}
		kept = append(kept, f)
	}
	rec.Failures = kept
	for k, d := range r.failed {
		i := slices.IndexFunc(rec.Failures, func(f Failure) bool { return f.key() == k })
		if i < 0 {
			rec.Failures = append(rec.Failures, Failure{Stage: k.stage, Scope: k.scope, Since: r.now})
			i = len(rec.Failures) - 1
		}
		f := &rec.Failures[i]
		f.Error, f.Event, f.Last = d, r.event, r.now
		changed = true
	}
	sortFailures(rec.Failures)
	if changed {
		if err := save(path, rec); err != nil {
			return rec, err
		}
	}
	return rec, nil
}

// load reads the record; an absent file is an empty record. A file that does not parse is an ERROR
// alongside the empty record, never a silent empty record: merge says so and replaces it.
func load(path string) (Record, error) {
	rec := Record{Schema: Schema}
	b, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return rec, nil
	}
	if err != nil {
		return rec, err
	}
	var got Record
	if err := json.Unmarshal(b, &got); err != nil || got.Schema != Schema {
		return rec, errUnreadable{path: path, err: err, schema: got.Schema}
	}
	rec.Failures = got.Failures
	return rec, nil
}

type errUnreadable struct {
	path   string
	err    error
	schema int
}

func (e errUnreadable) Error() string {
	if e.err != nil {
		return fmt.Sprintf("%s does not parse: %v", e.path, e.err)
	}
	return fmt.Sprintf("%s has schema %d, want %d", e.path, e.schema, Schema)
}

// save replaces the record by rename, so a reader never sees a half-written file. An empty record
// removes the file.
func save(path string, rec Record) error {
	if len(rec.Failures) == 0 {
		if err := os.Remove(path); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
		return nil
	}
	rec.Schema = Schema
	b, err := json.MarshalIndent(rec, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), "failures-*.json")
	if err != nil {
		return err
	}
	if _, err := tmp.Write(append(b, '\n')); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmp.Name())
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmp.Name())
		return err
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		_ = os.Remove(tmp.Name())
		return err
	}
	return nil
}

func sortFailures(fs []Failure) {
	slices.SortFunc(fs, func(a, b Failure) int {
		return cmp.Or(cmp.Compare(a.Stage, b.Stage), cmp.Compare(a.Scope, b.Scope))
	})
}

func render(speaker string, due []Failure, path string, persistErr error) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s: %d stage(s) failing — the session is unaffected; what it records is not:", speaker, len(due))
	for _, f := range due {
		where := ""
		if f.Scope != "" {
			where = " in " + f.Scope
		}
		fmt.Fprintf(&b, "\n- %s%s: %s (failing since %s, last at %s)",
			f.Stage, where, f.Error, f.Since.UTC().Format(time.RFC3339), f.Event)
	}
	if persistErr != nil {
		fmt.Fprintf(&b, "\nThis is shown on every displaying event while it lasts: the failure record cannot be kept (%v).", persistErr)
	} else {
		fmt.Fprintf(&b, "\nRecord: %s. Each entry clears when its stage next works; a failing stage is shown again after %d minutes.",
			path, int(NotifyEvery.Minutes()))
	}
	return b.String()
}
