package runlive

import (
	"os"
	"path/filepath"
	"testing"
)

// writeMarker plants .claude/run-live.json under a fresh project dir and returns it.
func writeMarker(t *testing.T, body string) string {
	t.Helper()
	dir := t.TempDir()
	claude := filepath.Join(dir, ".claude")
	if err := os.MkdirAll(claude, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(claude, "run-live.json"), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

// THE SHAPE THE OTHER MODULE ACTUALLY WRITES, read from bytes that module produced.
//
// testdata/run-live.golden.json is generated by frank-exchange-of-views' own writer and
// committed on both sides; scripts/check gates the two copies byte-for-byte. This test is
// the far end of that contract, and it is the one that was missing: every test in this file
// used to hand-write the shape it wished for, so all of them passed while the real file went
// unread. A hand-written fixture tests the reader against its author's memory; this one
// tests it against the writer.
func TestReadTheShapeTheWriterProduces(t *testing.T) {
	golden, err := os.ReadFile(filepath.Join("testdata", "run-live.golden.json"))
	if err != nil {
		t.Fatal(err)
	}
	st := Read(writeMarker(t, string(golden)))
	if st.Unrecognised {
		t.Fatal("the writer's own output must not read as an unrecognised shape")
	}
	if len(st.Runs) != 2 {
		t.Fatalf("want the golden's 2 open runs, got %d: %+v", len(st.Runs), st.Runs)
	}
	if !st.Live() {
		t.Error("two open runs must read as live")
	}
	if st.Runs[0].RunDir != "research/2026-07-18_alpha" {
		t.Errorf("runs[0].RunDir = %q", st.Runs[0].RunDir)
	}
	if st.Runs[0].Started != "2026-07-18T09:00:00.000Z" {
		t.Errorf("runs[0].Started = %q", st.Runs[0].Started)
	}
	if st.Runs[1].RunDir != "research/2026-07-18_beta" {
		t.Errorf("runs[1].RunDir = %q", st.Runs[1].RunDir)
	}
	// The union, de-duplicated: "research/old" is pinned by BOTH runs and must appear once.
	want := []string{"ideas/backlog.md", "research/old", "ideas/other.md"}
	got := st.Pinned()
	if len(got) != len(want) {
		t.Fatalf("pinned union = %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("pinned[%d] = %q, want %q", i, got[i], want[i])
		}
	}
}

// A READABLE FILE IN A SHAPE THIS READER DOES NOT KNOW IS NOT AN EMPTY RUN.
//
// This is the defect the whole change exists for, stated as a test. The list shape decoded
// into the old flat struct with every field zero, so the guards fired with nothing in them
// — "a research run is LIVE (, started )" — and an empty message reads as a working guard.
// The rule now: unknown shape means LIVE (fail open, a run may really be in progress) AND
// says so, so the next shape change announces itself instead of emptying the parentheses.
func TestAnUnknownShapeIsLiveAndSaysSo(t *testing.T) {
	for _, body := range []string{
		`{}`,
		`{"round":3,"seats":{"blue":"opus"}}`,
		`{"openRuns":[{"runDir":"research/x"}]}`, // a plausible NEXT rename
	} {
		st := Read(writeMarker(t, body))
		if !st.Unrecognised {
			t.Errorf("%s: want Unrecognised, got %+v", body, st)
		}
		if !st.Live() {
			t.Errorf("%s: an unreadable shape must still read as LIVE — a run may be in progress", body)
		}
		if len(st.Runs) != 0 {
			t.Errorf("%s: an unknown shape must not invent runs: %+v", body, st.Runs)
		}
		if d := st.Describe(); d == "" {
			t.Errorf("%s: Describe must name the unknown shape, not return empty", body)
		}
	}
}

// The retired singleton (pre-#529) is still read, so a marker left by an older writer — or
// by a machine that has not updated — is not invisible to the guards.
func TestTheRetiredFlatShapeIsStillRead(t *testing.T) {
	st := Read(writeMarker(t, `{"runDir":"research/2026-07-18_x","pinnedPaths":["ideas/backlog.md","research/old"],"started":"2026-07-18T09:00:00Z"}`))
	if st.Unrecognised {
		t.Fatal("the flat shape is known, not unrecognised")
	}
	if len(st.Runs) != 1 || st.Runs[0].RunDir != "research/2026-07-18_x" {
		t.Fatalf("flat marker must read as one run, got %+v", st.Runs)
	}
	if st.Runs[0].Started != "2026-07-18T09:00:00Z" {
		t.Errorf("started = %q", st.Runs[0].Started)
	}
	if len(st.Pinned()) != 2 {
		t.Errorf("pinned = %v", st.Pinned())
	}
}

// An EMPTY list is the file saying "nothing is open" — the one case that is genuinely not
// live, and it must be distinguishable from the unknown-shape case above. Without the
// distinction, closing the last run and failing to understand the file look identical.
func TestAnEmptyRunListIsNotLive(t *testing.T) {
	st := Read(writeMarker(t, `{"runs":[]}`))
	if st.Unrecognised {
		t.Error("a runs key that is present and empty is a KNOWN shape")
	}
	if st.Live() {
		t.Error("an empty run list means nothing is open")
	}
	if st.Describe() != "" {
		t.Errorf("nothing live must describe as empty, got %q", st.Describe())
	}
}

// The package contract: "missing or malformed marker both mean not live — guards fail
// open". Each case is one way the marker can be unreadable; every one MUST yield a state
// that is neither live nor unrecognised — there is no file to have a shape.
func TestReadFailsOpen(t *testing.T) {
	cases := []struct {
		name string
		dir  func(t *testing.T) string
	}{
		{"empty projectDir never reads a relative path", func(*testing.T) string { return "" }},
		{"no .claude directory at all", func(t *testing.T) string { return t.TempDir() }},
		{"malformed json", func(t *testing.T) string { return writeMarker(t, `{"runDir":`) }},
		{"truncated json", func(t *testing.T) string { return writeMarker(t, `{"runDir":"research/x"`) }},
		{"empty file", func(t *testing.T) string { return writeMarker(t, ``) }},
		{"json array, not an object", func(t *testing.T) string { return writeMarker(t, `["research/x"]`) }},
		{"wrong field type", func(t *testing.T) string { return writeMarker(t, `{"pinnedPaths":"not-a-list"}`) }},
		{"marker is a directory, not a file", func(t *testing.T) string {
			dir := t.TempDir()
			if err := os.MkdirAll(filepath.Join(dir, ".claude", "run-live.json"), 0o755); err != nil {
				t.Fatal(err)
			}
			return dir
		}},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			st := Read(c.dir(t))
			if st.Live() {
				t.Fatalf("want not live, got %+v", st)
			}
			if st.Unrecognised {
				t.Fatalf("an absent or unparseable FILE is not an unrecognised SHAPE: %+v", st)
			}
		})
	}
}

// The empty projectDir guard is load-bearing on its own: without it, filepath.Join
// would build the RELATIVE path ".claude/run-live.json" and the guard's verdict
// would depend on the caller's working directory. Planting exactly that file in
// the process's cwd must still read as "not live" when projectDir is empty.
func TestReadWithEmptyDirIgnoresCwdMarker(t *testing.T) {
	dir := writeMarker(t, `{"runs":[{"runDir":"research/cwd-trap"}]}`)
	t.Chdir(dir)
	if st := Read(""); st.Live() {
		t.Fatalf("empty projectDir must not resolve against cwd, got %+v", st)
	}
	// Sanity: the same marker IS live when the project dir is named explicitly,
	// proving the case above failed for the right reason.
	st := Read(dir)
	if len(st.Runs) != 1 || st.Runs[0].RunDir != "research/cwd-trap" {
		t.Fatalf("explicit projectDir should have read the marker, got %+v", st)
	}
}

// Unknown keys ALONGSIDE a known shape are forward-compatibility, not corruption: the
// writer may record more than this struct models, and that must not disarm the guards.
// This is the tolerance that is still wanted — it is only tolerance of a WHOLLY unknown
// shape that had to go.
func TestReadIgnoresUnknownFieldsBesideAKnownShape(t *testing.T) {
	st := Read(writeMarker(t, `{"runs":[{"runDir":"research/x","started":"t","phase":"round-3"}],"schemaVersion":9}`))
	if len(st.Runs) != 1 || st.Runs[0].RunDir != "research/x" || st.Runs[0].Started != "t" {
		t.Fatalf("unknown fields must be ignored, got %+v", st)
	}
}

// Describe is the single phrasing both guards use, so its shapes are pinned here rather
// than in each guard's test — two packages describing the same state independently is the
// smaller cousin of the drift this package exists to have survived.
func TestDescribeNamesEachState(t *testing.T) {
	if d := (State{}).Describe(); d != "" {
		t.Errorf("nothing live: %q", d)
	}
	one := State{Runs: []Marker{{RunDir: "research/x", Started: "t0"}}}
	if d := one.Describe(); d != "a research run is LIVE (research/x, started t0)" {
		t.Errorf("one run: %q", d)
	}
	two := State{Runs: []Marker{{RunDir: "research/x"}, {RunDir: "research/y"}}}
	if d := two.Describe(); d != "2 research runs are LIVE (research/x, research/y)" {
		t.Errorf("two runs: %q", d)
	}
}
