package toolchainnudge

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/ctoforaday/special-circumstances/plugins/prosthetic-conscience/tools/internal/hookunit"
	"github.com/ctoforaday/special-circumstances/plugins/prosthetic-conscience/tools/internal/runlive"
	"github.com/ctoforaday/special-circumstances/plugins/prosthetic-conscience/tools/internal/toolchain"
)

// allMissing / allPresent stand in for a PATH probe so a test's verdict never
// depends on what happens to be installed on the machine running it.
func allMissing(tools []toolchain.Tool) []toolchain.Status {
	out := make([]toolchain.Status, 0, len(tools))
	for _, t := range tools {
		out = append(out, toolchain.Status{Tool: t, Found: false})
	}
	return out
}

func allPresent(tools []toolchain.Tool) []toolchain.Status {
	out := make([]toolchain.Status, 0, len(tools))
	for _, t := range tools {
		out = append(out, toolchain.Status{Tool: t, Found: true})
	}
	return out
}

const manifest = `{"tools":[
  {"name":"qlty","tier":"recommended","check_cmd":"qlty --version"},
  {"name":"jq","tier":"optional","check_cmd":"jq --version"}
]}`

// pluginRoot writes a requirements.json (body "" means: write no file at all).
func pluginRoot(t *testing.T, body string) string {
	t.Helper()
	dir := t.TempDir()
	if body != "" {
		if err := os.WriteFile(filepath.Join(dir, "requirements.json"), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

// projectWithMarker plants a live-run marker (body "" means: no marker).
func projectWithMarker(t *testing.T, body string) string {
	t.Helper()
	dir := t.TempDir()
	if body != "" {
		claude := filepath.Join(dir, ".claude")
		if err := os.MkdirAll(claude, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(claude, "run-live.json"), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

// call drives the nudge through the unit the merged SessionStart binary registers.
//
// It used to drive a standalone `run` that nothing shipped — the #201 merge moved this into
// sc-sessionstart and left a second implementation behind, with its own manifest read and
// its own live-run check. These tests were exercising the copy that never runs.
//
// Exit code is always 0 by contract: a SessionStart hook that fails is a session that
// fails, and the merged binary owns the process boundary.
func call(t *testing.T, root, project string, probe func([]toolchain.Tool) []toolchain.Status, _ ...string) (string, int) {
	t.Helper()
	ctx := hookunit.NewCtx("SessionStart", nil, project, time.Time{})
	var out strings.Builder
	for _, r := range hookunit.Run(ctx, []hookunit.Unit{Unit(root, probe)}) {
		out.WriteString(r.Stdout)
	}
	return out.String(), 0
}

// liveMarker is the shape the frank-exchange-of-views writer ACTUALLY produces (a list of
// open runs, #529). It used to be the retired flat singleton, which is why this end-to-end
// path stayed green while the guard it exercises printed empty parentheses against every
// real marker: the fixture agreed with the reader, and both disagreed with the writer.
// internal/runlive/testdata/run-live.golden.json is the same shape, generated by that
// writer and gated against its copy in the other module.
const liveMarker = `{"runs":[{"runDir":"research/2026-07-18_x","pinnedPaths":["ideas/backlog.md"],"started":"2026-07-18T09:00:00Z","runId":"r1"}]}`

// unknownShapeMarker is a readable marker this reader does not understand. It must still
// announce a live run — fail open — and must say the shape is unrecognised rather than
// name an empty run, which is the whole defect this file's fixture used to hide.
const unknownShapeMarker = `{"openRuns":[{"runDir":"research/x"}]}`

func TestSessionStartNudges(t *testing.T) {
	cases := []struct {
		name     string
		manifest string
		marker   string
		probe    func([]toolchain.Tool) []toolchain.Status
		want     []string // substrings; nil = expect total silence
		wantLine int      // expected number of output lines
	}{
		{"healthy toolchain, no run: total silence", manifest, "", allPresent, nil, 0},
		{"missing recommended tool nudges once", manifest, "", allMissing, []string{"qlty", "doctor"}, 1},
		{"optional-only misses stay silent", `{"tools":[{"name":"jq","tier":"optional"}]}`, "", allMissing, nil, 0},
		{"live run is announced", manifest, liveMarker, allPresent, []string{"LIVE", "research/2026-07-18_x", "do NOT update plugins"}, 1},
		{"both nudges are separate lines", manifest, liveMarker, allMissing, []string{"qlty", "LIVE"}, 2},
		{"no plugin root still announces a live run", "", liveMarker, allMissing, []string{"LIVE"}, 1},
		{"malformed manifest degrades to silence, not error", `{"tools":`, "", allMissing, nil, 0},
		{"malformed manifest still announces a live run", `{"tools":`, liveMarker, allMissing, []string{"LIVE"}, 1},
		{"malformed marker is not a live run", manifest, `{"runDir":`, allPresent, nil, 0},
		{"a shape this reader cannot parse is announced as live AND as unrecognised", manifest, unknownShapeMarker, allPresent, []string{"UNRECOGNISED", "treat the run as LIVE"}, 1},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			out, code := call(t, pluginRoot(t, c.manifest), projectWithMarker(t, c.marker), c.probe)
			if code != 0 {
				t.Fatalf("exit %d; a SessionStart hook must never fail the session", code)
			}
			if len(c.want) == 0 {
				if out != "" {
					t.Fatalf("want silence, got %q", out)
				}
				return
			}
			for _, w := range c.want {
				if !strings.Contains(out, w) {
					t.Errorf("output = %q; missing %q", out, w)
				}
			}
			if got := len(strings.Split(strings.TrimRight(out, "\n"), "\n")); got != c.wantLine {
				t.Errorf("want %d line(s), got %d: %q", c.wantLine, got, out)
			}
		})
	}
}

// An absent plugin root and an absent manifest are the same silence, and neither may
// be read relative to the working directory.
func TestNoPluginRootReadsNothingRelative(t *testing.T) {
	cwd := t.TempDir()
	if err := os.WriteFile(filepath.Join(cwd, "requirements.json"), []byte(manifest), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Chdir(cwd)
	out, code := call(t, "", t.TempDir(), allMissing)
	if code != 0 || out != "" {
		t.Fatalf("empty plugin root must be silent, got %q (exit %d)", out, code)
	}
}

func TestLiveNudge(t *testing.T) {
	if got := liveNudge(runlive.State{}); got != "" {
		t.Fatalf("no marker must be silent, got %q", got)
	}
	m := runlive.State{Runs: []runlive.Marker{{RunDir: "research/x", Started: "2026-07-18T09:00:00Z"}}}
	got := liveNudge(m)
	for _, w := range []string{"research/x", "2026-07-18T09:00:00Z", "LIVE", "pinned paths"} {
		if !strings.Contains(got, w) {
			t.Errorf("liveNudge = %q; missing %q", got, w)
		}
	}
	if strings.Contains(got, "\n") {
		t.Errorf("the live nudge must be one line: %q", got)
	}
}
