// Code generated by scripts/schemagen from plugins/frank-exchange-of-views/requirements.json. DO NOT EDIT.

package record

// EventSchema is the event-shape epoch this binary writes.
//
// setup refuses to start a run when the binary's epoch differs from the one in the plugin's
// requirements.json. It answers one question — does this binary write the shape these prompts
// read — and it moves only when that shape changes incompatibly.
//
// It is not a version. Nothing here promises backwards compatibility, so there is no window
// to describe and no delta list to maintain: equal runs, unequal refuses.
const EventSchema = 1
