// Code generated by scripts/classgen from feov-memory/class-registry.json. DO NOT EDIT.

package record

import "github.com/ctoforaday/special-circumstances/plugins/frank-exchange-of-views/tools/internal/record/recordpb"

// ShippedMaterialDefaults is each shipped class's material_default, as this binary was built.
//
// The migrate verb reads it to translate a run whose staged registry or class coinings predate the
// field: a slug held here takes its value, and one absent takes by_grade as a stated fill. A
// class adopted into the registry after the build is absent here until the next build.
var ShippedMaterialDefaults = map[string]recordpb.ClassMaterial{
	"artifact-preservation":                  recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"audited-artifact-sibling-halo":          recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"causal-narrative-fails-reproduction":    recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"citation-figure-misattribution":         recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"citation-status-drift":                  recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"claim-contradicts-own-record":           recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"config-semantics-error":                 recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"cross-corpus-id-collision":              recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"cross-section-contradiction":            recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"derivation-status-overclaim":            recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"doctrine-vs-implementation":             recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"enumeration-non-exhaustive":             recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"exhaustive-sweep-omits-case":            recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"false-universal":                        recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"figure-miscomposition":                  recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"figure-recount-fails":                   recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"incomplete-repair-propagation":          recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"live-source-drift":                      recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"measurement-methodology-drift":          recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"metric-conflation":                      recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"missing-root-invariant":                 recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"name-keying-vs-marker":                  recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"negative-definition":                    recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"partial-control-coverage":               recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"policy-without-mechanism":               recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"pricing-basis-drift":                    recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"reader-channel-mismatch":                recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"recurrence-detector-keying":             recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"reflexivity-blindspot":                  recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"report-voice":                           recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"risk-coverage-omission":                 recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"self-attestation":                       recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"spec-underspecification":                recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"structure-noncompliance":                recordpb.ClassMaterial_CLASS_MATERIAL_NEVER,
	"undecided-disjunction":                  recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"unhandled-degenerate-case":              recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"unverified-composition":                 recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"verification-scope-blindspot":           recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
	"vote-laundering":                        recordpb.ClassMaterial_CLASS_MATERIAL_BY_GRADE,
	"within-source-condition-misattribution": recordpb.ClassMaterial_CLASS_MATERIAL_ALWAYS,
}
