// Code generated by scripts/classgen from feov-memory/class-registry.json. DO NOT EDIT.

package recordtest

// ShippedClasses is the gap-class vocabulary the plugin actually ships, in the order the
// registry holds it after sorting.
//
// Fixtures stage this rather than restating it. Three test files used to carry their own
// hand-written copy of all 38 slugs, under a comment pointing at the registry and nothing
// comparing them to it — so a rename would have left every fixture validating a vocabulary
// production had stopped accepting, with the suite green throughout.
var ShippedClasses = []string{
	"artifact-preservation",
	"audited-artifact-sibling-halo",
	"causal-narrative-fails-reproduction",
	"citation-figure-misattribution",
	"citation-status-drift",
	"claim-contradicts-own-record",
	"config-semantics-error",
	"cross-corpus-id-collision",
	"cross-section-contradiction",
	"derivation-status-overclaim",
	"doctrine-vs-implementation",
	"enumeration-non-exhaustive",
	"exhaustive-sweep-omits-case",
	"false-universal",
	"figure-miscomposition",
	"figure-recount-fails",
	"incomplete-repair-propagation",
	"live-source-drift",
	"measurement-methodology-drift",
	"metric-conflation",
	"missing-root-invariant",
	"name-keying-vs-marker",
	"negative-definition",
	"partial-control-coverage",
	"policy-without-mechanism",
	"pricing-basis-drift",
	"reader-channel-mismatch",
	"recurrence-detector-keying",
	"reflexivity-blindspot",
	"risk-coverage-omission",
	"self-attestation",
	"spec-underspecification",
	"undecided-disjunction",
	"unhandled-degenerate-case",
	"unverified-composition",
	"verification-scope-blindspot",
	"vote-laundering",
	"within-source-condition-misattribution",
}
